-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity update_knn is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    test_inst_V : IN STD_LOGIC_VECTOR (48 downto 0);
    train_inst_V : IN STD_LOGIC_VECTOR (47 downto 0);
    min_distances_V_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V12_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V2_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V3_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V14_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V15_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V16_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V17_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V28_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V29_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V210_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V211_read : IN STD_LOGIC_VECTOR (5 downto 0);
    min_distances_V_offset : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of update_knn is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";

    signal min_distances_V211_r_reg_1901 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_reg_pp0_iter1_min_distances_V211_r_reg_1901 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V210_r_reg_1909 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_reg_pp0_iter1_min_distances_V210_r_reg_1909 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V29_re_reg_1917 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_reg_pp0_iter1_min_distances_V29_re_reg_1917 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V28_re_reg_1925 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_reg_pp0_iter1_min_distances_V28_re_reg_1925 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V17_re_reg_1933 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_reg_pp0_iter1_min_distances_V17_re_reg_1933 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V16_re_reg_1941 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_reg_pp0_iter1_min_distances_V16_re_reg_1941 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V15_re_reg_1949 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_reg_pp0_iter1_min_distances_V15_re_reg_1949 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V14_re_reg_1957 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_reg_pp0_iter1_min_distances_V14_re_reg_1957 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V3_rea_reg_1965 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V2_rea_reg_1976 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V12_re_reg_1987 : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V_read_2_reg_1998 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_7_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_2009 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp51_fu_1360_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp51_reg_2017 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp75_fu_1450_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp75_reg_2022 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp86_fu_1550_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp86_reg_2027 : STD_LOGIC_VECTOR (3 downto 0);
    signal min_distances_V3_fu_1590_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_fu_1603_p14 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_9_fu_1634_p14 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_464_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_1621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_1652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_1683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_477_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_490_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_503_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_516_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_529_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_542_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_555_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp_fu_1745_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal phitmp4_fu_1752_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal phitmp5_fu_1759_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal phitmp6_fu_1766_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag15_3_reg_262 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag15_3_reg_262 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag15_3_reg_262 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_min_distances_V14_3_reg_278 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter1_min_distances_V14_3_reg_278 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag18_3_reg_291 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag18_3_reg_291 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag18_3_reg_291 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag12_1_reg_307 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag12_1_reg_307 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag12_1_reg_307 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag21_3_reg_320 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag21_3_reg_320 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag21_3_reg_320 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag24_3_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag24_3_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag24_3_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag8_1_reg_352 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag8_1_reg_352 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag8_1_reg_352 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag27_4_reg_365 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag27_4_reg_365 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag27_4_reg_365 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_min_distances_V28_4_reg_380 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter1_min_distances_V28_4_reg_380 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag31_4_reg_393 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag31_4_reg_393 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag31_4_reg_393 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag4_1_reg_408 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag4_1_reg_408 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag4_1_reg_408 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag36_4_reg_421 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag36_4_reg_421 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag36_4_reg_421 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag40_4_reg_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag40_4_reg_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag40_4_reg_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_write_flag_1_reg_451 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter1_write_flag_1_reg_451 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_phi_reg_pp0_iter2_write_flag_1_reg_451 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex_cast_fu_1556_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_56_fu_572_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal train_inst_V_cast_fu_568_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal r_V_fu_582_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_57_fu_588_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_596_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_608_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_fu_620_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_fu_632_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_fu_644_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_fu_656_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_64_fu_668_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_65_fu_680_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_fu_692_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_67_fu_704_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_68_fu_716_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_69_fu_728_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_70_fu_740_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_71_fu_752_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_72_fu_764_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_fu_776_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_74_fu_788_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_75_fu_800_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_76_fu_812_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_77_fu_824_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_78_fu_836_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_79_fu_848_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_fu_860_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_81_fu_872_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_82_fu_884_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_83_fu_896_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_fu_908_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_85_fu_920_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_86_fu_932_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_87_fu_944_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_88_fu_956_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_89_fu_968_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_90_fu_980_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_91_fu_992_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_92_fu_1004_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_93_fu_1016_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_94_fu_1028_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_95_fu_1040_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_96_fu_1052_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_97_fu_1064_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_98_fu_1076_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_99_fu_1088_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_100_fu_1100_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_101_fu_1112_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_102_fu_1124_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_103_fu_1136_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_104_fu_1148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_105_fu_1160_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_46_cast_fu_1156_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_44_cast_fu_1132_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp48_fu_1172_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_45_cast_fu_1144_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp49_fu_1178_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_43_cast_fu_1120_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_42_cast_fu_1108_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp50_fu_1188_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_41_cast_fu_1096_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp54_fu_1194_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp56_cast_fu_1200_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp54_cast_fu_1184_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp53_fu_1204_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_37_cast_fu_1048_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_36_cast_fu_1036_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp55_fu_1214_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_35_cast_fu_1024_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp56_fu_1220_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_40_cast_fu_1084_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_39_cast_fu_1072_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp57_fu_1230_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_38_cast_fu_1060_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp59_fu_1236_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp61_cast_fu_1242_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp59_cast_fu_1226_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp58_fu_1246_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp58_cast_fu_1252_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp53_cast_fu_1210_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp52_fu_1256_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_25_cast_fu_904_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_24_cast_fu_892_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp60_fu_1266_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_23_cast_fu_880_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp61_fu_1272_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_28_cast_fu_940_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_27_cast_fu_928_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp62_fu_1282_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_26_cast_fu_916_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp65_fu_1288_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp67_cast_fu_1294_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp65_cast_fu_1278_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp64_fu_1298_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_31_cast_fu_976_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_30_cast_fu_964_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp66_fu_1308_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_29_cast_fu_952_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp67_fu_1314_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_34_cast_fu_1012_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_33_cast_fu_1000_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp68_fu_1324_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_32_cast_fu_988_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp70_fu_1330_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp72_cast_fu_1336_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp70_cast_fu_1320_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp69_fu_1340_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp69_cast_fu_1346_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp64_cast_fu_1304_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp63_fu_1350_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp63_cast_fu_1356_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp52_cast_fu_1262_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_2_cast_fu_616_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_1_cast_fu_604_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp71_fu_1366_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_cast_fu_592_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp72_fu_1372_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_5_cast_fu_652_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_4_cast_fu_640_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp73_fu_1382_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_3_cast_fu_628_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp77_fu_1388_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp79_cast_fu_1394_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp77_cast_fu_1378_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp76_fu_1398_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_8_cast_fu_688_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_7_cast_fu_676_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp78_fu_1408_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_6_cast_fu_664_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp79_fu_1414_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_10_cast_fu_724_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_cast_5_fu_712_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp80_fu_1424_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_9_cast_fu_700_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp82_fu_1430_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp84_cast_fu_1436_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp82_cast_fu_1420_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp81_fu_1440_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp81_cast_fu_1446_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp76_cast_fu_1404_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_13_cast_fu_760_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_12_cast_fu_748_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp83_fu_1456_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_11_cast_fu_736_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp84_fu_1462_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_16_cast_fu_796_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_15_cast_fu_784_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp85_fu_1472_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_14_cast_fu_772_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp88_fu_1478_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp90_cast_fu_1484_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp88_cast_fu_1468_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp87_fu_1488_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_19_cast_fu_832_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_18_cast_fu_820_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp89_fu_1498_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_17_cast_fu_808_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp90_fu_1504_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_20_cast_fu_844_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_22_cast_fu_868_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp91_fu_1514_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_21_cast_fu_856_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_47_cast_fu_1168_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp93_fu_1524_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp97_cast_fu_1530_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp96_cast_fu_1520_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp94_fu_1534_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp93_cast_fu_1510_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp92_fu_1540_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp92_cast_fu_1546_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp87_cast_fu_1494_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp86_cast_fu_1577_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp75_cast_fu_1574_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp74_fu_1580_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp74_cast_fu_1586_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp51_cast_fu_1571_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_fu_1603_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_9_fu_1634_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1665_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_1665_p14 : STD_LOGIC_VECTOR (5 downto 0);
    signal write_flag_fu_1689_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal write_flag4_fu_1703_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal write_flag8_fu_1717_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal write_flag11_fu_1731_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal mrv_sel_fu_1773_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mrv_sel6_fu_1780_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mrv_sel7_fu_1787_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mrv_sel8_fu_1794_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mrv_sel9_fu_1801_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mrv_sel1_fu_1808_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mrv_sel2_fu_1815_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mrv_sel3_fu_1822_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal test_inst_V_int_reg : STD_LOGIC_VECTOR (48 downto 0);
    signal train_inst_V_int_reg : STD_LOGIC_VECTOR (47 downto 0);
    signal min_distances_V_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V12_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V2_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V3_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V14_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V15_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V16_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V17_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V28_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V29_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V210_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V211_read_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal min_distances_V_offset_int_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_5_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_6_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_7_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_8_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_9_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_10_int_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_11_int_reg : STD_LOGIC_VECTOR (5 downto 0);

    component digitrec_mux_42_1bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component digitrec_mux_124_cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        din3 : IN STD_LOGIC_VECTOR (5 downto 0);
        din4 : IN STD_LOGIC_VECTOR (5 downto 0);
        din5 : IN STD_LOGIC_VECTOR (5 downto 0);
        din6 : IN STD_LOGIC_VECTOR (5 downto 0);
        din7 : IN STD_LOGIC_VECTOR (5 downto 0);
        din8 : IN STD_LOGIC_VECTOR (5 downto 0);
        din9 : IN STD_LOGIC_VECTOR (5 downto 0);
        din10 : IN STD_LOGIC_VECTOR (5 downto 0);
        din11 : IN STD_LOGIC_VECTOR (5 downto 0);
        din12 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;



begin
    digitrec_mux_42_1bkb_U1 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_1,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_464_p6);

    digitrec_mux_42_1bkb_U2 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_477_p6);

    digitrec_mux_42_1bkb_U3 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_490_p6);

    digitrec_mux_42_1bkb_U4 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_1,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_503_p6);

    digitrec_mux_42_1bkb_U5 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_1,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_516_p6);

    digitrec_mux_42_1bkb_U6 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_529_p6);

    digitrec_mux_42_1bkb_U7 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_542_p6);

    digitrec_mux_42_1bkb_U8 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_1,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => grp_fu_555_p6);

    digitrec_mux_124_cud_U9 : component digitrec_mux_124_cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        din4_WIDTH => 6,
        din5_WIDTH => 6,
        din6_WIDTH => 6,
        din7_WIDTH => 6,
        din8_WIDTH => 6,
        din9_WIDTH => 6,
        din10_WIDTH => 6,
        din11_WIDTH => 6,
        din12_WIDTH => 4,
        dout_WIDTH => 6)
    port map (
        din0 => min_distances_V_read_2_reg_1998,
        din1 => min_distances_V12_re_reg_1987,
        din2 => min_distances_V2_rea_reg_1976,
        din3 => min_distances_V3_rea_reg_1965,
        din4 => min_distances_V14_re_reg_1957,
        din5 => min_distances_V15_re_reg_1949,
        din6 => min_distances_V16_re_reg_1941,
        din7 => min_distances_V17_re_reg_1933,
        din8 => min_distances_V28_re_reg_1925,
        din9 => min_distances_V29_re_reg_1917,
        din10 => min_distances_V210_r_reg_1909,
        din11 => min_distances_V211_r_reg_1901,
        din12 => tmp_8_fu_1603_p13,
        dout => tmp_8_fu_1603_p14);

    digitrec_mux_124_cud_U10 : component digitrec_mux_124_cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        din4_WIDTH => 6,
        din5_WIDTH => 6,
        din6_WIDTH => 6,
        din7_WIDTH => 6,
        din8_WIDTH => 6,
        din9_WIDTH => 6,
        din10_WIDTH => 6,
        din11_WIDTH => 6,
        din12_WIDTH => 4,
        dout_WIDTH => 6)
    port map (
        din0 => min_distances_V_read_2_reg_1998,
        din1 => min_distances_V12_re_reg_1987,
        din2 => min_distances_V2_rea_reg_1976,
        din3 => min_distances_V3_rea_reg_1965,
        din4 => min_distances_V14_re_reg_1957,
        din5 => min_distances_V15_re_reg_1949,
        din6 => min_distances_V16_re_reg_1941,
        din7 => min_distances_V17_re_reg_1933,
        din8 => min_distances_V28_re_reg_1925,
        din9 => min_distances_V29_re_reg_1917,
        din10 => min_distances_V210_r_reg_1909,
        din11 => min_distances_V211_r_reg_1901,
        din12 => tmp_9_fu_1634_p13,
        dout => tmp_9_fu_1634_p14);

    digitrec_mux_124_cud_U11 : component digitrec_mux_124_cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        din4_WIDTH => 6,
        din5_WIDTH => 6,
        din6_WIDTH => 6,
        din7_WIDTH => 6,
        din8_WIDTH => 6,
        din9_WIDTH => 6,
        din10_WIDTH => 6,
        din11_WIDTH => 6,
        din12_WIDTH => 4,
        dout_WIDTH => 6)
    port map (
        din0 => min_distances_V_read_2_reg_1998,
        din1 => min_distances_V12_re_reg_1987,
        din2 => min_distances_V2_rea_reg_1976,
        din3 => min_distances_V3_rea_reg_1965,
        din4 => min_distances_V14_re_reg_1957,
        din5 => min_distances_V15_re_reg_1949,
        din6 => min_distances_V16_re_reg_1941,
        din7 => min_distances_V17_re_reg_1933,
        din8 => min_distances_V28_re_reg_1925,
        din9 => min_distances_V29_re_reg_1917,
        din10 => min_distances_V210_r_reg_1909,
        din11 => min_distances_V211_r_reg_1901,
        din12 => tmp_s_fu_1665_p13,
        dout => tmp_s_fu_1665_p14);

    digitrec_mux_42_1bkb_U12 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_1,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => write_flag_fu_1689_p6);

    digitrec_mux_42_1bkb_U13 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => write_flag4_fu_1703_p6);

    digitrec_mux_42_1bkb_U14 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => newIndex_cast_fu_1556_p3,
        dout => write_flag8_fu_1717_p6);

    digitrec_mux_42_1bkb_U15 : component digitrec_mux_42_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_1,
        din4 => newIndex_cast_fu_1556_p3,
        dout => write_flag11_fu_1731_p6);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;

    ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 <= min_distances_V3_fu_1590_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 <= tmp_8_fu_1603_p14;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 <= ap_phi_reg_pp0_iter1_min_distances_V14_3_reg_278;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 <= min_distances_V3_fu_1590_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 <= tmp_9_fu_1634_p14;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 <= ap_phi_reg_pp0_iter1_min_distances_V28_4_reg_380;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag12_1_reg_307_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag12_1_reg_307 <= min_distances_V3_rea_reg_1965;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter2_write_flag12_1_reg_307 <= phitmp6_fu_1766_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag12_1_reg_307 <= ap_phi_reg_pp0_iter1_write_flag12_1_reg_307;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag15_3_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag15_3_reg_262 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag15_3_reg_262 <= grp_fu_555_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag15_3_reg_262 <= ap_phi_reg_pp0_iter1_write_flag15_3_reg_262;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag18_3_reg_291_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag18_3_reg_291 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag18_3_reg_291 <= grp_fu_542_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag18_3_reg_291 <= ap_phi_reg_pp0_iter1_write_flag18_3_reg_291;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag21_3_reg_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag21_3_reg_320 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag21_3_reg_320 <= grp_fu_529_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag21_3_reg_320 <= ap_phi_reg_pp0_iter1_write_flag21_3_reg_320;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag24_3_reg_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag24_3_reg_336 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag24_3_reg_336 <= grp_fu_516_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag24_3_reg_336 <= ap_phi_reg_pp0_iter1_write_flag24_3_reg_336;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag27_4_reg_365_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter2_write_flag27_4_reg_365 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag27_4_reg_365 <= grp_fu_503_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag27_4_reg_365 <= ap_phi_reg_pp0_iter1_write_flag27_4_reg_365;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag31_4_reg_393_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter2_write_flag31_4_reg_393 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag31_4_reg_393 <= grp_fu_490_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag31_4_reg_393 <= ap_phi_reg_pp0_iter1_write_flag31_4_reg_393;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag36_4_reg_421_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter2_write_flag36_4_reg_421 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag36_4_reg_421 <= grp_fu_477_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag36_4_reg_421 <= ap_phi_reg_pp0_iter1_write_flag36_4_reg_421;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag40_4_reg_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter2_write_flag40_4_reg_436 <= ap_const_lv1_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag40_4_reg_436 <= grp_fu_464_p6;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag40_4_reg_436 <= ap_phi_reg_pp0_iter1_write_flag40_4_reg_436;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag4_1_reg_408_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag4_1_reg_408 <= min_distances_V12_re_reg_1987;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter2_write_flag4_1_reg_408 <= phitmp4_fu_1752_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag4_1_reg_408 <= ap_phi_reg_pp0_iter1_write_flag4_1_reg_408;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag8_1_reg_352_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag8_1_reg_352 <= min_distances_V2_rea_reg_1976;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter2_write_flag8_1_reg_352 <= phitmp5_fu_1759_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag8_1_reg_352 <= ap_phi_reg_pp0_iter1_write_flag8_1_reg_352;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_write_flag_1_reg_451_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_5_fu_1652_p2 = ap_const_lv1_1) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_0) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_6_fu_1683_p2 = ap_const_lv1_1) and (tmp_5_fu_1652_p2 = ap_const_lv1_0) and (tmp_fu_1621_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter2_write_flag_1_reg_451 <= min_distances_V_read_2_reg_1998;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (tmp_fu_1621_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter2_write_flag_1_reg_451 <= phitmp_fu_1745_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter2_write_flag_1_reg_451 <= ap_phi_reg_pp0_iter1_write_flag_1_reg_451;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                ap_phi_reg_pp0_iter1_min_distances_V14_3_reg_278 <= ap_phi_reg_pp0_iter0_min_distances_V14_3_reg_278;
                ap_phi_reg_pp0_iter1_min_distances_V28_4_reg_380 <= ap_phi_reg_pp0_iter0_min_distances_V28_4_reg_380;
                ap_phi_reg_pp0_iter1_write_flag12_1_reg_307 <= ap_phi_reg_pp0_iter0_write_flag12_1_reg_307;
                ap_phi_reg_pp0_iter1_write_flag15_3_reg_262 <= ap_phi_reg_pp0_iter0_write_flag15_3_reg_262;
                ap_phi_reg_pp0_iter1_write_flag18_3_reg_291 <= ap_phi_reg_pp0_iter0_write_flag18_3_reg_291;
                ap_phi_reg_pp0_iter1_write_flag21_3_reg_320 <= ap_phi_reg_pp0_iter0_write_flag21_3_reg_320;
                ap_phi_reg_pp0_iter1_write_flag24_3_reg_336 <= ap_phi_reg_pp0_iter0_write_flag24_3_reg_336;
                ap_phi_reg_pp0_iter1_write_flag27_4_reg_365 <= ap_phi_reg_pp0_iter0_write_flag27_4_reg_365;
                ap_phi_reg_pp0_iter1_write_flag31_4_reg_393 <= ap_phi_reg_pp0_iter0_write_flag31_4_reg_393;
                ap_phi_reg_pp0_iter1_write_flag36_4_reg_421 <= ap_phi_reg_pp0_iter0_write_flag36_4_reg_421;
                ap_phi_reg_pp0_iter1_write_flag40_4_reg_436 <= ap_phi_reg_pp0_iter0_write_flag40_4_reg_436;
                ap_phi_reg_pp0_iter1_write_flag4_1_reg_408 <= ap_phi_reg_pp0_iter0_write_flag4_1_reg_408;
                ap_phi_reg_pp0_iter1_write_flag8_1_reg_352 <= ap_phi_reg_pp0_iter0_write_flag8_1_reg_352;
                ap_phi_reg_pp0_iter1_write_flag_1_reg_451 <= ap_phi_reg_pp0_iter0_write_flag_1_reg_451;
                ap_reg_pp0_iter1_min_distances_V14_re_reg_1957 <= min_distances_V14_re_reg_1957;
                ap_reg_pp0_iter1_min_distances_V15_re_reg_1949 <= min_distances_V15_re_reg_1949;
                ap_reg_pp0_iter1_min_distances_V16_re_reg_1941 <= min_distances_V16_re_reg_1941;
                ap_reg_pp0_iter1_min_distances_V17_re_reg_1933 <= min_distances_V17_re_reg_1933;
                ap_reg_pp0_iter1_min_distances_V210_r_reg_1909 <= min_distances_V210_r_reg_1909;
                ap_reg_pp0_iter1_min_distances_V211_r_reg_1901 <= min_distances_V211_r_reg_1901;
                ap_reg_pp0_iter1_min_distances_V28_re_reg_1925 <= min_distances_V28_re_reg_1925;
                ap_reg_pp0_iter1_min_distances_V29_re_reg_1917 <= min_distances_V29_re_reg_1917;
                min_distances_V12_re_reg_1987 <= min_distances_V12_read_int_reg;
                min_distances_V14_re_reg_1957 <= min_distances_V14_read_int_reg;
                min_distances_V15_re_reg_1949 <= min_distances_V15_read_int_reg;
                min_distances_V16_re_reg_1941 <= min_distances_V16_read_int_reg;
                min_distances_V17_re_reg_1933 <= min_distances_V17_read_int_reg;
                min_distances_V210_r_reg_1909 <= min_distances_V210_read_int_reg;
                min_distances_V211_r_reg_1901 <= min_distances_V211_read_int_reg;
                min_distances_V28_re_reg_1925 <= min_distances_V28_read_int_reg;
                min_distances_V29_re_reg_1917 <= min_distances_V29_read_int_reg;
                min_distances_V2_rea_reg_1976 <= min_distances_V2_read_int_reg;
                min_distances_V3_rea_reg_1965 <= min_distances_V3_read_int_reg;
                min_distances_V_read_2_reg_1998 <= min_distances_V_read_int_reg;
                tmp51_reg_2017 <= tmp51_fu_1360_p2;
                tmp75_reg_2022 <= tmp75_fu_1450_p2;
                tmp86_reg_2027 <= tmp86_fu_1550_p2;
                tmp_7_reg_2009 <= tmp_7_fu_576_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= ap_phi_reg_pp0_iter2_write_flag_1_reg_451;
                ap_return_10_int_reg <= mrv_sel2_fu_1815_p3;
                ap_return_11_int_reg <= mrv_sel3_fu_1822_p3;
                ap_return_1_int_reg <= ap_phi_reg_pp0_iter2_write_flag4_1_reg_408;
                ap_return_2_int_reg <= ap_phi_reg_pp0_iter2_write_flag8_1_reg_352;
                ap_return_3_int_reg <= ap_phi_reg_pp0_iter2_write_flag12_1_reg_307;
                ap_return_4_int_reg <= mrv_sel_fu_1773_p3;
                ap_return_5_int_reg <= mrv_sel6_fu_1780_p3;
                ap_return_6_int_reg <= mrv_sel7_fu_1787_p3;
                ap_return_7_int_reg <= mrv_sel8_fu_1794_p3;
                ap_return_8_int_reg <= mrv_sel9_fu_1801_p3;
                ap_return_9_int_reg <= mrv_sel1_fu_1808_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                min_distances_V12_read_int_reg <= min_distances_V12_read;
                min_distances_V14_read_int_reg <= min_distances_V14_read;
                min_distances_V15_read_int_reg <= min_distances_V15_read;
                min_distances_V16_read_int_reg <= min_distances_V16_read;
                min_distances_V17_read_int_reg <= min_distances_V17_read;
                min_distances_V210_read_int_reg <= min_distances_V210_read;
                min_distances_V211_read_int_reg <= min_distances_V211_read;
                min_distances_V28_read_int_reg <= min_distances_V28_read;
                min_distances_V29_read_int_reg <= min_distances_V29_read;
                min_distances_V2_read_int_reg <= min_distances_V2_read;
                min_distances_V3_read_int_reg <= min_distances_V3_read;
                min_distances_V_offset_int_reg <= min_distances_V_offset;
                min_distances_V_read_int_reg <= min_distances_V_read;
                test_inst_V_int_reg <= test_inst_V;
                train_inst_V_int_reg <= train_inst_V;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_phi_reg_pp0_iter0_min_distances_V14_3_reg_278 <= "XXXXXX";
    ap_phi_reg_pp0_iter0_min_distances_V28_4_reg_380 <= "XXXXXX";
    ap_phi_reg_pp0_iter0_write_flag12_1_reg_307 <= "XXXXXX";
    ap_phi_reg_pp0_iter0_write_flag15_3_reg_262 <= "X";
    ap_phi_reg_pp0_iter0_write_flag18_3_reg_291 <= "X";
    ap_phi_reg_pp0_iter0_write_flag21_3_reg_320 <= "X";
    ap_phi_reg_pp0_iter0_write_flag24_3_reg_336 <= "X";
    ap_phi_reg_pp0_iter0_write_flag27_4_reg_365 <= "X";
    ap_phi_reg_pp0_iter0_write_flag31_4_reg_393 <= "X";
    ap_phi_reg_pp0_iter0_write_flag36_4_reg_421 <= "X";
    ap_phi_reg_pp0_iter0_write_flag40_4_reg_436 <= "X";
    ap_phi_reg_pp0_iter0_write_flag4_1_reg_408 <= "XXXXXX";
    ap_phi_reg_pp0_iter0_write_flag8_1_reg_352 <= "XXXXXX";
    ap_phi_reg_pp0_iter0_write_flag_1_reg_451 <= "XXXXXX";

    ap_return_0_assign_proc : process(ap_phi_reg_pp0_iter2_write_flag_1_reg_451, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= ap_phi_reg_pp0_iter2_write_flag_1_reg_451;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_phi_reg_pp0_iter2_write_flag4_1_reg_408, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= ap_phi_reg_pp0_iter2_write_flag4_1_reg_408;
        end if; 
    end process;


    ap_return_10_assign_proc : process(mrv_sel2_fu_1815_p3, ap_ce_reg, ap_return_10_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_10 <= ap_return_10_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_10 <= mrv_sel2_fu_1815_p3;
        end if; 
    end process;


    ap_return_11_assign_proc : process(mrv_sel3_fu_1822_p3, ap_ce_reg, ap_return_11_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_11 <= ap_return_11_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_11 <= mrv_sel3_fu_1822_p3;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_phi_reg_pp0_iter2_write_flag8_1_reg_352, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= ap_phi_reg_pp0_iter2_write_flag8_1_reg_352;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_phi_reg_pp0_iter2_write_flag12_1_reg_307, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= ap_phi_reg_pp0_iter2_write_flag12_1_reg_307;
        end if; 
    end process;


    ap_return_4_assign_proc : process(mrv_sel_fu_1773_p3, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= mrv_sel_fu_1773_p3;
        end if; 
    end process;


    ap_return_5_assign_proc : process(mrv_sel6_fu_1780_p3, ap_ce_reg, ap_return_5_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_5 <= ap_return_5_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_5 <= mrv_sel6_fu_1780_p3;
        end if; 
    end process;


    ap_return_6_assign_proc : process(mrv_sel7_fu_1787_p3, ap_ce_reg, ap_return_6_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_6 <= ap_return_6_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_6 <= mrv_sel7_fu_1787_p3;
        end if; 
    end process;


    ap_return_7_assign_proc : process(mrv_sel8_fu_1794_p3, ap_ce_reg, ap_return_7_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_7 <= ap_return_7_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_7 <= mrv_sel8_fu_1794_p3;
        end if; 
    end process;


    ap_return_8_assign_proc : process(mrv_sel9_fu_1801_p3, ap_ce_reg, ap_return_8_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_8 <= ap_return_8_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_8 <= mrv_sel9_fu_1801_p3;
        end if; 
    end process;


    ap_return_9_assign_proc : process(mrv_sel1_fu_1808_p3, ap_ce_reg, ap_return_9_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_9 <= ap_return_9_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_9 <= mrv_sel1_fu_1808_p3;
        end if; 
    end process;

    min_distances_V3_fu_1590_p2 <= std_logic_vector(unsigned(tmp74_cast_fu_1586_p1) + unsigned(tmp51_cast_fu_1571_p1));
    mrv_sel1_fu_1808_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 when (ap_phi_reg_pp0_iter2_write_flag31_4_reg_393(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V29_re_reg_1917;
    mrv_sel2_fu_1815_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 when (ap_phi_reg_pp0_iter2_write_flag36_4_reg_421(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V210_r_reg_1909;
    mrv_sel3_fu_1822_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 when (ap_phi_reg_pp0_iter2_write_flag40_4_reg_436(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V211_r_reg_1901;
    mrv_sel6_fu_1780_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 when (ap_phi_reg_pp0_iter2_write_flag18_3_reg_291(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V15_re_reg_1949;
    mrv_sel7_fu_1787_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 when (ap_phi_reg_pp0_iter2_write_flag21_3_reg_320(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V16_re_reg_1941;
    mrv_sel8_fu_1794_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 when (ap_phi_reg_pp0_iter2_write_flag24_3_reg_336(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V17_re_reg_1933;
    mrv_sel9_fu_1801_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V28_4_reg_380 when (ap_phi_reg_pp0_iter2_write_flag27_4_reg_365(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V28_re_reg_1925;
    mrv_sel_fu_1773_p3 <= 
        ap_phi_reg_pp0_iter2_min_distances_V14_3_reg_278 when (ap_phi_reg_pp0_iter2_write_flag15_3_reg_262(0) = '1') else 
        ap_reg_pp0_iter1_min_distances_V14_re_reg_1957;
    newIndex_cast_fu_1556_p3 <= 
        ap_const_lv2_0 when (tmp_7_reg_2009(0) = '1') else 
        ap_const_lv2_1;
    phitmp4_fu_1752_p3 <= 
        min_distances_V3_fu_1590_p2 when (write_flag4_fu_1703_p6(0) = '1') else 
        min_distances_V12_re_reg_1987;
    phitmp5_fu_1759_p3 <= 
        min_distances_V3_fu_1590_p2 when (write_flag8_fu_1717_p6(0) = '1') else 
        min_distances_V2_rea_reg_1976;
    phitmp6_fu_1766_p3 <= 
        min_distances_V3_fu_1590_p2 when (write_flag11_fu_1731_p6(0) = '1') else 
        min_distances_V3_rea_reg_1965;
    phitmp_fu_1745_p3 <= 
        min_distances_V3_fu_1590_p2 when (write_flag_fu_1689_p6(0) = '1') else 
        min_distances_V_read_2_reg_1998;
    r_V_fu_582_p2 <= (train_inst_V_cast_fu_568_p1 xor test_inst_V_int_reg);
    tmp48_fu_1172_p2 <= std_logic_vector(unsigned(tmp_1_46_cast_fu_1156_p1) + unsigned(tmp_1_44_cast_fu_1132_p1));
    tmp49_fu_1178_p2 <= std_logic_vector(unsigned(tmp48_fu_1172_p2) + unsigned(tmp_1_45_cast_fu_1144_p1));
    tmp50_fu_1188_p2 <= std_logic_vector(unsigned(tmp_1_43_cast_fu_1120_p1) + unsigned(tmp_1_42_cast_fu_1108_p1));
    tmp51_cast_fu_1571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp51_reg_2017),6));
    tmp51_fu_1360_p2 <= std_logic_vector(unsigned(tmp63_cast_fu_1356_p1) + unsigned(tmp52_cast_fu_1262_p1));
    tmp52_cast_fu_1262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp52_fu_1256_p2),5));
    tmp52_fu_1256_p2 <= std_logic_vector(unsigned(tmp58_cast_fu_1252_p1) + unsigned(tmp53_cast_fu_1210_p1));
    tmp53_cast_fu_1210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp53_fu_1204_p2),4));
    tmp53_fu_1204_p2 <= std_logic_vector(unsigned(tmp56_cast_fu_1200_p1) + unsigned(tmp54_cast_fu_1184_p1));
    tmp54_cast_fu_1184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp49_fu_1178_p2),3));
    tmp54_fu_1194_p2 <= std_logic_vector(unsigned(tmp50_fu_1188_p2) + unsigned(tmp_1_41_cast_fu_1096_p1));
    tmp55_fu_1214_p2 <= std_logic_vector(unsigned(tmp_1_37_cast_fu_1048_p1) + unsigned(tmp_1_36_cast_fu_1036_p1));
    tmp56_cast_fu_1200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp54_fu_1194_p2),3));
    tmp56_fu_1220_p2 <= std_logic_vector(unsigned(tmp55_fu_1214_p2) + unsigned(tmp_1_35_cast_fu_1024_p1));
    tmp57_fu_1230_p2 <= std_logic_vector(unsigned(tmp_1_40_cast_fu_1084_p1) + unsigned(tmp_1_39_cast_fu_1072_p1));
    tmp58_cast_fu_1252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp58_fu_1246_p2),4));
    tmp58_fu_1246_p2 <= std_logic_vector(unsigned(tmp61_cast_fu_1242_p1) + unsigned(tmp59_cast_fu_1226_p1));
    tmp59_cast_fu_1226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp56_fu_1220_p2),3));
    tmp59_fu_1236_p2 <= std_logic_vector(unsigned(tmp57_fu_1230_p2) + unsigned(tmp_1_38_cast_fu_1060_p1));
    tmp60_fu_1266_p2 <= std_logic_vector(unsigned(tmp_1_25_cast_fu_904_p1) + unsigned(tmp_1_24_cast_fu_892_p1));
    tmp61_cast_fu_1242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp59_fu_1236_p2),3));
    tmp61_fu_1272_p2 <= std_logic_vector(unsigned(tmp60_fu_1266_p2) + unsigned(tmp_1_23_cast_fu_880_p1));
    tmp62_fu_1282_p2 <= std_logic_vector(unsigned(tmp_1_28_cast_fu_940_p1) + unsigned(tmp_1_27_cast_fu_928_p1));
    tmp63_cast_fu_1356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp63_fu_1350_p2),5));
    tmp63_fu_1350_p2 <= std_logic_vector(unsigned(tmp69_cast_fu_1346_p1) + unsigned(tmp64_cast_fu_1304_p1));
    tmp64_cast_fu_1304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp64_fu_1298_p2),4));
    tmp64_fu_1298_p2 <= std_logic_vector(unsigned(tmp67_cast_fu_1294_p1) + unsigned(tmp65_cast_fu_1278_p1));
    tmp65_cast_fu_1278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp61_fu_1272_p2),3));
    tmp65_fu_1288_p2 <= std_logic_vector(unsigned(tmp62_fu_1282_p2) + unsigned(tmp_1_26_cast_fu_916_p1));
    tmp66_fu_1308_p2 <= std_logic_vector(unsigned(tmp_1_31_cast_fu_976_p1) + unsigned(tmp_1_30_cast_fu_964_p1));
    tmp67_cast_fu_1294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp65_fu_1288_p2),3));
    tmp67_fu_1314_p2 <= std_logic_vector(unsigned(tmp66_fu_1308_p2) + unsigned(tmp_1_29_cast_fu_952_p1));
    tmp68_fu_1324_p2 <= std_logic_vector(unsigned(tmp_1_34_cast_fu_1012_p1) + unsigned(tmp_1_33_cast_fu_1000_p1));
    tmp69_cast_fu_1346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp69_fu_1340_p2),4));
    tmp69_fu_1340_p2 <= std_logic_vector(unsigned(tmp72_cast_fu_1336_p1) + unsigned(tmp70_cast_fu_1320_p1));
    tmp70_cast_fu_1320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp67_fu_1314_p2),3));
    tmp70_fu_1330_p2 <= std_logic_vector(unsigned(tmp68_fu_1324_p2) + unsigned(tmp_1_32_cast_fu_988_p1));
    tmp71_fu_1366_p2 <= std_logic_vector(unsigned(tmp_1_2_cast_fu_616_p1) + unsigned(tmp_1_1_cast_fu_604_p1));
    tmp72_cast_fu_1336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp70_fu_1330_p2),3));
    tmp72_fu_1372_p2 <= std_logic_vector(unsigned(tmp71_fu_1366_p2) + unsigned(tmp_1_cast_fu_592_p1));
    tmp73_fu_1382_p2 <= std_logic_vector(unsigned(tmp_1_5_cast_fu_652_p1) + unsigned(tmp_1_4_cast_fu_640_p1));
    tmp74_cast_fu_1586_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp74_fu_1580_p2),6));
    tmp74_fu_1580_p2 <= std_logic_vector(unsigned(tmp86_cast_fu_1577_p1) + unsigned(tmp75_cast_fu_1574_p1));
    tmp75_cast_fu_1574_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp75_reg_2022),5));
    tmp75_fu_1450_p2 <= std_logic_vector(unsigned(tmp81_cast_fu_1446_p1) + unsigned(tmp76_cast_fu_1404_p1));
    tmp76_cast_fu_1404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp76_fu_1398_p2),4));
    tmp76_fu_1398_p2 <= std_logic_vector(unsigned(tmp79_cast_fu_1394_p1) + unsigned(tmp77_cast_fu_1378_p1));
    tmp77_cast_fu_1378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp72_fu_1372_p2),3));
    tmp77_fu_1388_p2 <= std_logic_vector(unsigned(tmp73_fu_1382_p2) + unsigned(tmp_1_3_cast_fu_628_p1));
    tmp78_fu_1408_p2 <= std_logic_vector(unsigned(tmp_1_8_cast_fu_688_p1) + unsigned(tmp_1_7_cast_fu_676_p1));
    tmp79_cast_fu_1394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp77_fu_1388_p2),3));
    tmp79_fu_1414_p2 <= std_logic_vector(unsigned(tmp78_fu_1408_p2) + unsigned(tmp_1_6_cast_fu_664_p1));
    tmp80_fu_1424_p2 <= std_logic_vector(unsigned(tmp_1_10_cast_fu_724_p1) + unsigned(tmp_1_cast_5_fu_712_p1));
    tmp81_cast_fu_1446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp81_fu_1440_p2),4));
    tmp81_fu_1440_p2 <= std_logic_vector(unsigned(tmp84_cast_fu_1436_p1) + unsigned(tmp82_cast_fu_1420_p1));
    tmp82_cast_fu_1420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp79_fu_1414_p2),3));
    tmp82_fu_1430_p2 <= std_logic_vector(unsigned(tmp80_fu_1424_p2) + unsigned(tmp_1_9_cast_fu_700_p1));
    tmp83_fu_1456_p2 <= std_logic_vector(unsigned(tmp_1_13_cast_fu_760_p1) + unsigned(tmp_1_12_cast_fu_748_p1));
    tmp84_cast_fu_1436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp82_fu_1430_p2),3));
    tmp84_fu_1462_p2 <= std_logic_vector(unsigned(tmp83_fu_1456_p2) + unsigned(tmp_1_11_cast_fu_736_p1));
    tmp85_fu_1472_p2 <= std_logic_vector(unsigned(tmp_1_16_cast_fu_796_p1) + unsigned(tmp_1_15_cast_fu_784_p1));
    tmp86_cast_fu_1577_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp86_reg_2027),5));
    tmp86_fu_1550_p2 <= std_logic_vector(unsigned(tmp92_cast_fu_1546_p1) + unsigned(tmp87_cast_fu_1494_p1));
    tmp87_cast_fu_1494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp87_fu_1488_p2),4));
    tmp87_fu_1488_p2 <= std_logic_vector(unsigned(tmp90_cast_fu_1484_p1) + unsigned(tmp88_cast_fu_1468_p1));
    tmp88_cast_fu_1468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp84_fu_1462_p2),3));
    tmp88_fu_1478_p2 <= std_logic_vector(unsigned(tmp85_fu_1472_p2) + unsigned(tmp_1_14_cast_fu_772_p1));
    tmp89_fu_1498_p2 <= std_logic_vector(unsigned(tmp_1_19_cast_fu_832_p1) + unsigned(tmp_1_18_cast_fu_820_p1));
    tmp90_cast_fu_1484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp88_fu_1478_p2),3));
    tmp90_fu_1504_p2 <= std_logic_vector(unsigned(tmp89_fu_1498_p2) + unsigned(tmp_1_17_cast_fu_808_p1));
    tmp91_fu_1514_p2 <= std_logic_vector(unsigned(tmp_1_20_cast_fu_844_p1) + unsigned(tmp_1_22_cast_fu_868_p1));
    tmp92_cast_fu_1546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp92_fu_1540_p2),4));
    tmp92_fu_1540_p2 <= std_logic_vector(unsigned(tmp94_fu_1534_p2) + unsigned(tmp93_cast_fu_1510_p1));
    tmp93_cast_fu_1510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp90_fu_1504_p2),3));
    tmp93_fu_1524_p2 <= std_logic_vector(unsigned(tmp_1_21_cast_fu_856_p1) + unsigned(tmp_1_47_cast_fu_1168_p1));
    tmp94_fu_1534_p2 <= std_logic_vector(unsigned(tmp97_cast_fu_1530_p1) + unsigned(tmp96_cast_fu_1520_p1));
    tmp96_cast_fu_1520_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp91_fu_1514_p2),3));
    tmp97_cast_fu_1530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp93_fu_1524_p2),3));
    tmp_100_fu_1100_p3 <= r_V_fu_582_p2(43 downto 43);
    tmp_101_fu_1112_p3 <= r_V_fu_582_p2(44 downto 44);
    tmp_102_fu_1124_p3 <= r_V_fu_582_p2(45 downto 45);
    tmp_103_fu_1136_p3 <= r_V_fu_582_p2(46 downto 46);
    tmp_104_fu_1148_p3 <= r_V_fu_582_p2(47 downto 47);
    tmp_105_fu_1160_p3 <= r_V_fu_582_p2(48 downto 48);
    tmp_1_10_cast_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_68_fu_716_p3),2));
    tmp_1_11_cast_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_69_fu_728_p3),2));
    tmp_1_12_cast_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_70_fu_740_p3),2));
    tmp_1_13_cast_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_71_fu_752_p3),2));
    tmp_1_14_cast_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_72_fu_764_p3),2));
    tmp_1_15_cast_fu_784_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_73_fu_776_p3),2));
    tmp_1_16_cast_fu_796_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_74_fu_788_p3),2));
    tmp_1_17_cast_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_75_fu_800_p3),2));
    tmp_1_18_cast_fu_820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_76_fu_812_p3),2));
    tmp_1_19_cast_fu_832_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_77_fu_824_p3),2));
    tmp_1_1_cast_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_58_fu_596_p3),2));
    tmp_1_20_cast_fu_844_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_78_fu_836_p3),2));
    tmp_1_21_cast_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_79_fu_848_p3),2));
    tmp_1_22_cast_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_80_fu_860_p3),2));
    tmp_1_23_cast_fu_880_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_81_fu_872_p3),2));
    tmp_1_24_cast_fu_892_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_82_fu_884_p3),2));
    tmp_1_25_cast_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_83_fu_896_p3),2));
    tmp_1_26_cast_fu_916_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_84_fu_908_p3),2));
    tmp_1_27_cast_fu_928_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_85_fu_920_p3),2));
    tmp_1_28_cast_fu_940_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_86_fu_932_p3),2));
    tmp_1_29_cast_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_87_fu_944_p3),2));
    tmp_1_2_cast_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_59_fu_608_p3),2));
    tmp_1_30_cast_fu_964_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_88_fu_956_p3),2));
    tmp_1_31_cast_fu_976_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_89_fu_968_p3),2));
    tmp_1_32_cast_fu_988_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_90_fu_980_p3),2));
    tmp_1_33_cast_fu_1000_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_91_fu_992_p3),2));
    tmp_1_34_cast_fu_1012_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_92_fu_1004_p3),2));
    tmp_1_35_cast_fu_1024_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_93_fu_1016_p3),2));
    tmp_1_36_cast_fu_1036_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_94_fu_1028_p3),2));
    tmp_1_37_cast_fu_1048_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_95_fu_1040_p3),2));
    tmp_1_38_cast_fu_1060_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_96_fu_1052_p3),2));
    tmp_1_39_cast_fu_1072_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_97_fu_1064_p3),2));
    tmp_1_3_cast_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_60_fu_620_p3),2));
    tmp_1_40_cast_fu_1084_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_98_fu_1076_p3),2));
    tmp_1_41_cast_fu_1096_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_99_fu_1088_p3),2));
    tmp_1_42_cast_fu_1108_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_100_fu_1100_p3),2));
    tmp_1_43_cast_fu_1120_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_101_fu_1112_p3),2));
    tmp_1_44_cast_fu_1132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_102_fu_1124_p3),2));
    tmp_1_45_cast_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_103_fu_1136_p3),2));
    tmp_1_46_cast_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_104_fu_1148_p3),2));
    tmp_1_47_cast_fu_1168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_105_fu_1160_p3),2));
    tmp_1_4_cast_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_61_fu_632_p3),2));
    tmp_1_5_cast_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_62_fu_644_p3),2));
    tmp_1_6_cast_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_63_fu_656_p3),2));
    tmp_1_7_cast_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_64_fu_668_p3),2));
    tmp_1_8_cast_fu_688_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_65_fu_680_p3),2));
    tmp_1_9_cast_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_66_fu_692_p3),2));
    tmp_1_cast_5_fu_712_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_67_fu_704_p3),2));
    tmp_1_cast_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_57_fu_588_p1),2));
    tmp_56_fu_572_p1 <= min_distances_V_offset_int_reg(2 - 1 downto 0);
    tmp_57_fu_588_p1 <= r_V_fu_582_p2(1 - 1 downto 0);
    tmp_58_fu_596_p3 <= r_V_fu_582_p2(1 downto 1);
    tmp_59_fu_608_p3 <= r_V_fu_582_p2(2 downto 2);
    tmp_5_fu_1652_p2 <= "1" when (unsigned(min_distances_V3_fu_1590_p2) < unsigned(tmp_9_fu_1634_p14)) else "0";
    tmp_60_fu_620_p3 <= r_V_fu_582_p2(3 downto 3);
    tmp_61_fu_632_p3 <= r_V_fu_582_p2(4 downto 4);
    tmp_62_fu_644_p3 <= r_V_fu_582_p2(5 downto 5);
    tmp_63_fu_656_p3 <= r_V_fu_582_p2(6 downto 6);
    tmp_64_fu_668_p3 <= r_V_fu_582_p2(7 downto 7);
    tmp_65_fu_680_p3 <= r_V_fu_582_p2(8 downto 8);
    tmp_66_fu_692_p3 <= r_V_fu_582_p2(9 downto 9);
    tmp_67_fu_704_p3 <= r_V_fu_582_p2(10 downto 10);
    tmp_68_fu_716_p3 <= r_V_fu_582_p2(11 downto 11);
    tmp_69_fu_728_p3 <= r_V_fu_582_p2(12 downto 12);
    tmp_6_fu_1683_p2 <= "1" when (unsigned(min_distances_V3_fu_1590_p2) < unsigned(tmp_s_fu_1665_p14)) else "0";
    tmp_70_fu_740_p3 <= r_V_fu_582_p2(13 downto 13);
    tmp_71_fu_752_p3 <= r_V_fu_582_p2(14 downto 14);
    tmp_72_fu_764_p3 <= r_V_fu_582_p2(15 downto 15);
    tmp_73_fu_776_p3 <= r_V_fu_582_p2(16 downto 16);
    tmp_74_fu_788_p3 <= r_V_fu_582_p2(17 downto 17);
    tmp_75_fu_800_p3 <= r_V_fu_582_p2(18 downto 18);
    tmp_76_fu_812_p3 <= r_V_fu_582_p2(19 downto 19);
    tmp_77_fu_824_p3 <= r_V_fu_582_p2(20 downto 20);
    tmp_78_fu_836_p3 <= r_V_fu_582_p2(21 downto 21);
    tmp_79_fu_848_p3 <= r_V_fu_582_p2(22 downto 22);
    tmp_7_fu_576_p2 <= "0" when (tmp_56_fu_572_p1 = ap_const_lv2_3) else "1";
    tmp_80_fu_860_p3 <= r_V_fu_582_p2(23 downto 23);
    tmp_81_fu_872_p3 <= r_V_fu_582_p2(24 downto 24);
    tmp_82_fu_884_p3 <= r_V_fu_582_p2(25 downto 25);
    tmp_83_fu_896_p3 <= r_V_fu_582_p2(26 downto 26);
    tmp_84_fu_908_p3 <= r_V_fu_582_p2(27 downto 27);
    tmp_85_fu_920_p3 <= r_V_fu_582_p2(28 downto 28);
    tmp_86_fu_932_p3 <= r_V_fu_582_p2(29 downto 29);
    tmp_87_fu_944_p3 <= r_V_fu_582_p2(30 downto 30);
    tmp_88_fu_956_p3 <= r_V_fu_582_p2(31 downto 31);
    tmp_89_fu_968_p3 <= r_V_fu_582_p2(32 downto 32);
    tmp_8_fu_1603_p13 <= 
        ap_const_lv4_0 when (tmp_7_reg_2009(0) = '1') else 
        ap_const_lv4_1;
    tmp_90_fu_980_p3 <= r_V_fu_582_p2(33 downto 33);
    tmp_91_fu_992_p3 <= r_V_fu_582_p2(34 downto 34);
    tmp_92_fu_1004_p3 <= r_V_fu_582_p2(35 downto 35);
    tmp_93_fu_1016_p3 <= r_V_fu_582_p2(36 downto 36);
    tmp_94_fu_1028_p3 <= r_V_fu_582_p2(37 downto 37);
    tmp_95_fu_1040_p3 <= r_V_fu_582_p2(38 downto 38);
    tmp_96_fu_1052_p3 <= r_V_fu_582_p2(39 downto 39);
    tmp_97_fu_1064_p3 <= r_V_fu_582_p2(40 downto 40);
    tmp_98_fu_1076_p3 <= r_V_fu_582_p2(41 downto 41);
    tmp_99_fu_1088_p3 <= r_V_fu_582_p2(42 downto 42);
    tmp_9_fu_1634_p13 <= 
        ap_const_lv4_4 when (tmp_7_reg_2009(0) = '1') else 
        ap_const_lv4_5;
    tmp_fu_1621_p2 <= "1" when (unsigned(min_distances_V3_fu_1590_p2) < unsigned(tmp_8_fu_1603_p14)) else "0";
    tmp_s_fu_1665_p13 <= 
        ap_const_lv4_8 when (tmp_7_reg_2009(0) = '1') else 
        ap_const_lv4_9;
    train_inst_V_cast_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(train_inst_V_int_reg),49));
end behav;
