// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module update_knn (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        test_inst_V,
        train_inst_V,
        min_distances_V_address0,
        min_distances_V_ce0,
        min_distances_V_we0,
        min_distances_V_d0,
        min_distances_V_q0,
        min_distances_V_address1,
        min_distances_V_ce1,
        min_distances_V_we1,
        min_distances_V_d1,
        min_distances_V_offset
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [48:0] test_inst_V;
input  [47:0] train_inst_V;
output  [4:0] min_distances_V_address0;
output   min_distances_V_ce0;
output   min_distances_V_we0;
output  [5:0] min_distances_V_d0;
input  [5:0] min_distances_V_q0;
output  [4:0] min_distances_V_address1;
output   min_distances_V_ce1;
output   min_distances_V_we1;
output  [5:0] min_distances_V_d1;
input  [3:0] min_distances_V_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] min_distances_V_address0;
reg min_distances_V_ce0;
reg min_distances_V_we0;
reg[5:0] min_distances_V_d0;
reg min_distances_V_ce1;
reg min_distances_V_we1;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] tmp_1_fu_138_p2;
reg   [5:0] tmp_1_reg_246;
wire   [48:0] r_V_fu_148_p2;
reg   [48:0] r_V_reg_252;
wire   [5:0] i_fu_164_p2;
wire    ap_CS_fsm_state2;
wire   [5:0] dist_V_fu_181_p2;
wire   [0:0] exitcond_fu_158_p2;
reg   [4:0] min_distances_V_addr_reg_280;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_4_fu_192_p2;
reg   [5:0] min_distance_last_el_1_reg_285;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_6_fu_216_p2;
reg   [0:0] tmp_6_reg_291;
reg   [4:0] min_distances_V_addr_1_reg_295;
wire   [1:0] grp_fu_120_p2;
wire    ap_CS_fsm_state5;
reg   [5:0] min_distance_last_el_reg_86;
reg   [5:0] bvh_d_index_reg_97;
reg   [1:0] i1_reg_108;
wire  signed [63:0] tmp_2_cast_fu_207_p1;
wire  signed [63:0] tmp_3_cast_fu_231_p1;
reg   [5:0] temp_min_distance_la_fu_40;
wire   [0:0] tmp_9_fu_241_p2;
wire   [5:0] tmp_fu_130_p3;
wire   [5:0] min_distances_V_offs_1_fu_126_p1;
wire   [48:0] train_inst_V_cast_fu_144_p1;
wire   [31:0] index_assign_cast2_fu_154_p1;
wire   [0:0] tmp_5_fu_170_p3;
wire   [5:0] tmp_1_cast_fu_177_p1;
wire   [5:0] tmp_5_cast_fu_198_p1;
wire   [5:0] tmp_2_fu_202_p2;
wire   [5:0] tmp_8_cast_fu_222_p1;
wire   [5:0] tmp_3_fu_226_p2;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        bvh_d_index_reg_97 <= i_fu_164_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        bvh_d_index_reg_97 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_reg_108 <= 2'd2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i1_reg_108 <= grp_fu_120_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        min_distance_last_el_reg_86 <= dist_V_fu_181_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        min_distance_last_el_reg_86 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        temp_min_distance_la_fu_40 <= min_distances_V_q0;
    end else if (((exitcond_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        temp_min_distance_la_fu_40 <= min_distance_last_el_reg_86;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        min_distance_last_el_1_reg_285 <= min_distances_V_q0;
        tmp_6_reg_291 <= tmp_6_fu_216_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        min_distances_V_addr_1_reg_295 <= tmp_3_cast_fu_231_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_4_fu_192_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        min_distances_V_addr_reg_280 <= tmp_2_cast_fu_207_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        r_V_reg_252 <= r_V_fu_148_p2;
        tmp_1_reg_246 <= tmp_1_fu_138_p2;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_192_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_fu_192_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((tmp_6_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        min_distances_V_address0 = min_distances_V_addr_reg_280;
    end else if (((tmp_6_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        min_distances_V_address0 = tmp_3_cast_fu_231_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        min_distances_V_address0 = tmp_2_cast_fu_207_p1;
    end else begin
        min_distances_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((tmp_6_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_6_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        min_distances_V_ce0 = 1'b1;
    end else begin
        min_distances_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        min_distances_V_ce1 = 1'b1;
    end else begin
        min_distances_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        min_distances_V_d0 = min_distances_V_q0;
    end else if (((tmp_6_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        min_distances_V_d0 = temp_min_distance_la_fu_40;
    end else begin
        min_distances_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_fu_241_p2 == 1'd1) & (tmp_6_reg_291 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_6_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        min_distances_V_we0 = 1'b1;
    end else begin
        min_distances_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_9_fu_241_p2 == 1'd1) & (tmp_6_reg_291 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        min_distances_V_we1 = 1'b1;
    end else begin
        min_distances_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_4_fu_192_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign dist_V_fu_181_p2 = (min_distance_last_el_reg_86 + tmp_1_cast_fu_177_p1);

assign exitcond_fu_158_p2 = ((bvh_d_index_reg_97 == 6'd49) ? 1'b1 : 1'b0);

assign grp_fu_120_p2 = ($signed(i1_reg_108) + $signed(2'd3));

assign i_fu_164_p2 = (bvh_d_index_reg_97 + 6'd1);

assign index_assign_cast2_fu_154_p1 = bvh_d_index_reg_97;

assign min_distances_V_address1 = min_distances_V_addr_1_reg_295;

assign min_distances_V_d1 = min_distance_last_el_1_reg_285;

assign min_distances_V_offs_1_fu_126_p1 = min_distances_V_offset;

assign r_V_fu_148_p2 = (train_inst_V_cast_fu_144_p1 ^ test_inst_V);

assign tmp_1_cast_fu_177_p1 = tmp_5_fu_170_p3;

assign tmp_1_fu_138_p2 = (tmp_fu_130_p3 - min_distances_V_offs_1_fu_126_p1);

assign tmp_2_cast_fu_207_p1 = $signed(tmp_2_fu_202_p2);

assign tmp_2_fu_202_p2 = (tmp_1_reg_246 + tmp_5_cast_fu_198_p1);

assign tmp_3_cast_fu_231_p1 = $signed(tmp_3_fu_226_p2);

assign tmp_3_fu_226_p2 = (tmp_1_reg_246 + tmp_8_cast_fu_222_p1);

assign tmp_4_fu_192_p2 = ((i1_reg_108 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_5_cast_fu_198_p1 = i1_reg_108;

assign tmp_5_fu_170_p3 = r_V_reg_252[index_assign_cast2_fu_154_p1];

assign tmp_6_fu_216_p2 = ((temp_min_distance_la_fu_40 < min_distances_V_q0) ? 1'b1 : 1'b0);

assign tmp_8_cast_fu_222_p1 = grp_fu_120_p2;

assign tmp_9_fu_241_p2 = ((min_distance_last_el_1_reg_285 < min_distances_V_q0) ? 1'b1 : 1'b0);

assign tmp_fu_130_p3 = {{min_distances_V_offset}, {2'd0}};

assign train_inst_V_cast_fu_144_p1 = train_inst_V;

endmodule //update_knn
