// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool knn_vote::ap_const_boolean_1 = true;
const bool knn_vote::ap_const_boolean_0 = false;
const sc_lv<8> knn_vote::ap_const_lv8_96 = "10010110";
const sc_lv<2> knn_vote::ap_const_lv2_3 = "11";
const sc_lv<2> knn_vote::ap_const_lv2_2 = "10";
const sc_lv<3> knn_vote::ap_const_lv3_5 = "101";
const sc_lv<3> knn_vote::ap_const_lv3_4 = "100";
const sc_lv<3> knn_vote::ap_const_lv3_7 = "111";
const sc_lv<3> knn_vote::ap_const_lv3_6 = "110";
const sc_lv<4> knn_vote::ap_const_lv4_9 = "1001";
const sc_lv<4> knn_vote::ap_const_lv4_8 = "1000";
const sc_logic knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic knn_vote::ap_const_logic_0 = sc_dt::Log_0;

knn_vote::knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_10_fu_740_p2 );
    sensitive << ( tmp_1_fu_733_p3 );
    sensitive << ( tmp_10_cast_fu_730_p1 );

    SC_METHOD(thread_sum_distances_0_2_fu_292_p2);
    sensitive << ( tmp_1_0_1_cast_fu_274_p1 );
    sensitive << ( tmp30_cast_fu_288_p1 );

    SC_METHOD(thread_sum_distances_1_2_fu_334_p2);
    sensitive << ( tmp_1_1_1_cast_fu_316_p1 );
    sensitive << ( tmp31_cast_fu_330_p1 );

    SC_METHOD(thread_sum_distances_1_min_1_fu_570_p3);
    sensitive << ( sum_distances_1_min_s_reg_752 );
    sensitive << ( sum_distances_1_2_reg_757 );
    sensitive << ( tmp_8_1_reg_762 );

    SC_METHOD(thread_sum_distances_1_min_2_fu_580_p3);
    sensitive << ( sum_distances_2_2_reg_768 );
    sensitive << ( sum_distances_1_min_1_fu_570_p3 );
    sensitive << ( tmp_8_2_fu_575_p2 );

    SC_METHOD(thread_sum_distances_1_min_3_fu_592_p3);
    sensitive << ( sum_distances_3_2_reg_774 );
    sensitive << ( sum_distances_1_min_2_fu_580_p3 );
    sensitive << ( tmp_8_3_fu_587_p2 );

    SC_METHOD(thread_sum_distances_1_min_4_fu_628_p3);
    sensitive << ( ap_reg_pp0_iter1_sum_distances_4_2_reg_780 );
    sensitive << ( sum_distances_1_min_3_reg_815 );
    sensitive << ( tmp_8_4_fu_624_p2 );

    SC_METHOD(thread_sum_distances_1_min_5_fu_639_p3);
    sensitive << ( ap_reg_pp0_iter1_sum_distances_5_2_reg_786 );
    sensitive << ( sum_distances_1_min_4_fu_628_p3 );
    sensitive << ( tmp_8_5_fu_634_p2 );

    SC_METHOD(thread_sum_distances_1_min_6_fu_676_p3);
    sensitive << ( ap_reg_pp0_iter2_sum_distances_6_2_reg_792 );
    sensitive << ( sum_distances_1_min_5_reg_826 );
    sensitive << ( tmp_8_6_reg_831 );

    SC_METHOD(thread_sum_distances_1_min_7_fu_686_p3);
    sensitive << ( ap_reg_pp0_iter2_sum_distances_7_2_reg_798 );
    sensitive << ( sum_distances_1_min_6_fu_676_p3 );
    sensitive << ( tmp_8_7_fu_681_p2 );

    SC_METHOD(thread_sum_distances_1_min_8_fu_698_p3);
    sensitive << ( ap_reg_pp0_iter2_sum_distances_8_2_reg_804 );
    sensitive << ( tmp_8_8_fu_693_p2 );
    sensitive << ( sum_distances_1_min_7_fu_686_p3 );

    SC_METHOD(thread_sum_distances_1_min_s_fu_304_p3);
    sensitive << ( sum_distances_0_2_fu_292_p2 );
    sensitive << ( tmp_8_fu_298_p2 );

    SC_METHOD(thread_sum_distances_2_2_fu_368_p2);
    sensitive << ( tmp_1_2_1_cast_fu_350_p1 );
    sensitive << ( tmp32_cast_fu_364_p1 );

    SC_METHOD(thread_sum_distances_3_2_fu_396_p2);
    sensitive << ( tmp_1_3_1_cast_fu_378_p1 );
    sensitive << ( tmp33_cast_fu_392_p1 );

    SC_METHOD(thread_sum_distances_4_2_fu_424_p2);
    sensitive << ( tmp_1_4_1_cast_fu_406_p1 );
    sensitive << ( tmp34_cast_fu_420_p1 );

    SC_METHOD(thread_sum_distances_5_2_fu_452_p2);
    sensitive << ( tmp_1_5_1_cast_fu_434_p1 );
    sensitive << ( tmp35_cast_fu_448_p1 );

    SC_METHOD(thread_sum_distances_6_2_fu_480_p2);
    sensitive << ( tmp_1_6_1_cast_fu_462_p1 );
    sensitive << ( tmp36_cast_fu_476_p1 );

    SC_METHOD(thread_sum_distances_7_2_fu_508_p2);
    sensitive << ( tmp_1_7_1_cast_fu_490_p1 );
    sensitive << ( tmp37_cast_fu_504_p1 );

    SC_METHOD(thread_sum_distances_8_2_fu_536_p2);
    sensitive << ( tmp_1_8_1_cast_fu_518_p1 );
    sensitive << ( tmp38_cast_fu_532_p1 );

    SC_METHOD(thread_sum_distances_9_2_fu_564_p2);
    sensitive << ( tmp_1_9_1_cast_fu_546_p1 );
    sensitive << ( tmp39_cast_fu_560_p1 );

    SC_METHOD(thread_tmp30_cast_fu_288_p1);
    sensitive << ( tmp30_fu_282_p2 );

    SC_METHOD(thread_tmp30_fu_282_p2);
    sensitive << ( tmp_1_0_2_cast_fu_278_p1 );
    sensitive << ( tmp_1_cast_fu_270_p1 );

    SC_METHOD(thread_tmp31_cast_fu_330_p1);
    sensitive << ( tmp31_fu_324_p2 );

    SC_METHOD(thread_tmp31_fu_324_p2);
    sensitive << ( tmp_1_1_2_cast_fu_320_p1 );
    sensitive << ( tmp_1_1_cast_fu_312_p1 );

    SC_METHOD(thread_tmp32_cast_fu_364_p1);
    sensitive << ( tmp32_fu_358_p2 );

    SC_METHOD(thread_tmp32_fu_358_p2);
    sensitive << ( tmp_1_2_2_cast_fu_354_p1 );
    sensitive << ( tmp_1_2_cast_fu_346_p1 );

    SC_METHOD(thread_tmp33_cast_fu_392_p1);
    sensitive << ( tmp33_fu_386_p2 );

    SC_METHOD(thread_tmp33_fu_386_p2);
    sensitive << ( tmp_1_3_2_cast_fu_382_p1 );
    sensitive << ( tmp_1_3_cast_fu_374_p1 );

    SC_METHOD(thread_tmp34_cast_fu_420_p1);
    sensitive << ( tmp34_fu_414_p2 );

    SC_METHOD(thread_tmp34_fu_414_p2);
    sensitive << ( tmp_1_4_2_cast_fu_410_p1 );
    sensitive << ( tmp_1_4_cast_fu_402_p1 );

    SC_METHOD(thread_tmp35_cast_fu_448_p1);
    sensitive << ( tmp35_fu_442_p2 );

    SC_METHOD(thread_tmp35_fu_442_p2);
    sensitive << ( tmp_1_5_2_cast_fu_438_p1 );
    sensitive << ( tmp_1_5_cast_fu_430_p1 );

    SC_METHOD(thread_tmp36_cast_fu_476_p1);
    sensitive << ( tmp36_fu_470_p2 );

    SC_METHOD(thread_tmp36_fu_470_p2);
    sensitive << ( tmp_1_6_2_cast_fu_466_p1 );
    sensitive << ( tmp_1_6_cast_fu_458_p1 );

    SC_METHOD(thread_tmp37_cast_fu_504_p1);
    sensitive << ( tmp37_fu_498_p2 );

    SC_METHOD(thread_tmp37_fu_498_p2);
    sensitive << ( tmp_1_7_2_cast_fu_494_p1 );
    sensitive << ( tmp_1_7_cast_fu_486_p1 );

    SC_METHOD(thread_tmp38_cast_fu_532_p1);
    sensitive << ( tmp38_fu_526_p2 );

    SC_METHOD(thread_tmp38_fu_526_p2);
    sensitive << ( tmp_1_8_2_cast_fu_522_p1 );
    sensitive << ( tmp_1_8_cast_fu_514_p1 );

    SC_METHOD(thread_tmp39_cast_fu_560_p1);
    sensitive << ( tmp39_fu_554_p2 );

    SC_METHOD(thread_tmp39_fu_554_p2);
    sensitive << ( tmp_1_9_2_cast_fu_550_p1 );
    sensitive << ( tmp_1_9_cast_fu_542_p1 );

    SC_METHOD(thread_tmp_10_cast_fu_730_p1);
    sensitive << ( tmp_3_reg_853 );

    SC_METHOD(thread_tmp_10_fu_740_p2);
    sensitive << ( tmp_8_8_reg_842 );
    sensitive << ( tmp_8_9_reg_847 );

    SC_METHOD(thread_tmp_1_0_1_cast_fu_274_p1);
    sensitive << ( knn_set_0_1_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_0_2_cast_fu_278_p1);
    sensitive << ( knn_set_0_2_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_1_1_cast_fu_316_p1);
    sensitive << ( knn_set_1_1_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_1_2_cast_fu_320_p1);
    sensitive << ( knn_set_1_2_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_1_cast_fu_312_p1);
    sensitive << ( knn_set_1_0_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_2_1_cast_fu_350_p1);
    sensitive << ( knn_set_2_1_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_2_2_cast_fu_354_p1);
    sensitive << ( knn_set_2_2_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_2_cast_fu_346_p1);
    sensitive << ( knn_set_2_0_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_3_1_cast_fu_378_p1);
    sensitive << ( knn_set_0_1_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_3_2_cast_fu_382_p1);
    sensitive << ( knn_set_0_2_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_3_cast_fu_374_p1);
    sensitive << ( knn_set_0_0_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_4_1_cast_fu_406_p1);
    sensitive << ( knn_set_1_1_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_4_2_cast_fu_410_p1);
    sensitive << ( knn_set_1_2_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_4_cast_fu_402_p1);
    sensitive << ( knn_set_1_0_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_5_1_cast_fu_434_p1);
    sensitive << ( knn_set_2_1_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_5_2_cast_fu_438_p1);
    sensitive << ( knn_set_2_2_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_5_cast_fu_430_p1);
    sensitive << ( knn_set_2_0_1_V_r_int_reg );

    SC_METHOD(thread_tmp_1_6_1_cast_fu_462_p1);
    sensitive << ( knn_set_0_1_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_6_2_cast_fu_466_p1);
    sensitive << ( knn_set_0_2_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_6_cast_fu_458_p1);
    sensitive << ( knn_set_0_0_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_7_1_cast_fu_490_p1);
    sensitive << ( knn_set_1_1_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_7_2_cast_fu_494_p1);
    sensitive << ( knn_set_1_2_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_7_cast_fu_486_p1);
    sensitive << ( knn_set_1_0_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_8_1_cast_fu_518_p1);
    sensitive << ( knn_set_2_1_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_8_2_cast_fu_522_p1);
    sensitive << ( knn_set_2_2_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_8_cast_fu_514_p1);
    sensitive << ( knn_set_2_0_2_V_r_int_reg );

    SC_METHOD(thread_tmp_1_9_1_cast_fu_546_p1);
    sensitive << ( knn_set_0_1_3_V_r_int_reg );

    SC_METHOD(thread_tmp_1_9_2_cast_fu_550_p1);
    sensitive << ( knn_set_0_2_3_V_r_int_reg );

    SC_METHOD(thread_tmp_1_9_cast_fu_542_p1);
    sensitive << ( knn_set_0_0_3_V_r_int_reg );

    SC_METHOD(thread_tmp_1_cast_fu_270_p1);
    sensitive << ( knn_set_0_0_0_V_r_int_reg );

    SC_METHOD(thread_tmp_1_fu_733_p3);
    sensitive << ( tmp_8_9_reg_847 );

    SC_METHOD(thread_tmp_2_fu_668_p3);
    sensitive << ( tmp_s_fu_662_p2 );
    sensitive << ( tmp_9_fu_654_p3 );
    sensitive << ( tmp_7_cast_fu_651_p1 );

    SC_METHOD(thread_tmp_3_cast_cast_fu_710_p3);
    sensitive << ( tmp_8_7_fu_681_p2 );

    SC_METHOD(thread_tmp_3_fu_723_p3);
    sensitive << ( tmp_2_reg_837 );
    sensitive << ( tmp_4_fu_718_p2 );
    sensitive << ( tmp_3_cast_cast_fu_710_p3 );

    SC_METHOD(thread_tmp_4_fu_718_p2);
    sensitive << ( tmp_8_6_reg_831 );
    sensitive << ( tmp_8_7_fu_681_p2 );

    SC_METHOD(thread_tmp_5_fu_602_p3);
    sensitive << ( tmp_8_3_fu_587_p2 );

    SC_METHOD(thread_tmp_6_fu_610_p2);
    sensitive << ( tmp_8_2_fu_575_p2 );
    sensitive << ( tmp_8_3_fu_587_p2 );

    SC_METHOD(thread_tmp_7_cast_fu_651_p1);
    sensitive << ( tmp_7_reg_821 );

    SC_METHOD(thread_tmp_7_fu_616_p3);
    sensitive << ( tmp_6_fu_610_p2 );
    sensitive << ( tmp_5_fu_602_p3 );
    sensitive << ( tmp_cast_fu_599_p1 );

    SC_METHOD(thread_tmp_8_1_fu_340_p2);
    sensitive << ( sum_distances_1_min_s_fu_304_p3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sum_distances_1_2_fu_334_p2 );

    SC_METHOD(thread_tmp_8_2_fu_575_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sum_distances_2_2_reg_768 );
    sensitive << ( sum_distances_1_min_1_fu_570_p3 );

    SC_METHOD(thread_tmp_8_3_fu_587_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sum_distances_3_2_reg_774 );
    sensitive << ( sum_distances_1_min_2_fu_580_p3 );

    SC_METHOD(thread_tmp_8_4_fu_624_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter1_sum_distances_4_2_reg_780 );
    sensitive << ( sum_distances_1_min_3_reg_815 );

    SC_METHOD(thread_tmp_8_5_fu_634_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter1_sum_distances_5_2_reg_786 );
    sensitive << ( sum_distances_1_min_4_fu_628_p3 );

    SC_METHOD(thread_tmp_8_6_fu_646_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter1_sum_distances_6_2_reg_792 );
    sensitive << ( sum_distances_1_min_5_fu_639_p3 );

    SC_METHOD(thread_tmp_8_7_fu_681_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter2_sum_distances_7_2_reg_798 );
    sensitive << ( sum_distances_1_min_6_fu_676_p3 );

    SC_METHOD(thread_tmp_8_8_fu_693_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter2_sum_distances_8_2_reg_804 );
    sensitive << ( sum_distances_1_min_7_fu_686_p3 );

    SC_METHOD(thread_tmp_8_9_fu_705_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter2_sum_distances_9_2_reg_810 );
    sensitive << ( sum_distances_1_min_8_fu_698_p3 );

    SC_METHOD(thread_tmp_8_fu_298_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sum_distances_0_2_fu_292_p2 );

    SC_METHOD(thread_tmp_9_fu_654_p3);
    sensitive << ( tmp_8_5_fu_634_p2 );

    SC_METHOD(thread_tmp_cast_fu_599_p1);
    sensitive << ( tmp_8_1_reg_762 );

    SC_METHOD(thread_tmp_s_fu_662_p2);
    sensitive << ( tmp_8_4_fu_624_p2 );
    sensitive << ( tmp_8_5_fu_634_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, knn_set_0_0_0_V_r, "(port)knn_set_0_0_0_V_r");
    sc_trace(mVcdFile, knn_set_0_0_1_V_r, "(port)knn_set_0_0_1_V_r");
    sc_trace(mVcdFile, knn_set_0_0_2_V_r, "(port)knn_set_0_0_2_V_r");
    sc_trace(mVcdFile, knn_set_0_0_3_V_r, "(port)knn_set_0_0_3_V_r");
    sc_trace(mVcdFile, knn_set_0_1_0_V_r, "(port)knn_set_0_1_0_V_r");
    sc_trace(mVcdFile, knn_set_0_1_1_V_r, "(port)knn_set_0_1_1_V_r");
    sc_trace(mVcdFile, knn_set_0_1_2_V_r, "(port)knn_set_0_1_2_V_r");
    sc_trace(mVcdFile, knn_set_0_1_3_V_r, "(port)knn_set_0_1_3_V_r");
    sc_trace(mVcdFile, knn_set_0_2_0_V_r, "(port)knn_set_0_2_0_V_r");
    sc_trace(mVcdFile, knn_set_0_2_1_V_r, "(port)knn_set_0_2_1_V_r");
    sc_trace(mVcdFile, knn_set_0_2_2_V_r, "(port)knn_set_0_2_2_V_r");
    sc_trace(mVcdFile, knn_set_0_2_3_V_r, "(port)knn_set_0_2_3_V_r");
    sc_trace(mVcdFile, knn_set_1_0_0_V_r, "(port)knn_set_1_0_0_V_r");
    sc_trace(mVcdFile, knn_set_1_0_1_V_r, "(port)knn_set_1_0_1_V_r");
    sc_trace(mVcdFile, knn_set_1_0_2_V_r, "(port)knn_set_1_0_2_V_r");
    sc_trace(mVcdFile, knn_set_1_1_0_V_r, "(port)knn_set_1_1_0_V_r");
    sc_trace(mVcdFile, knn_set_1_1_1_V_r, "(port)knn_set_1_1_1_V_r");
    sc_trace(mVcdFile, knn_set_1_1_2_V_r, "(port)knn_set_1_1_2_V_r");
    sc_trace(mVcdFile, knn_set_1_2_0_V_r, "(port)knn_set_1_2_0_V_r");
    sc_trace(mVcdFile, knn_set_1_2_1_V_r, "(port)knn_set_1_2_1_V_r");
    sc_trace(mVcdFile, knn_set_1_2_2_V_r, "(port)knn_set_1_2_2_V_r");
    sc_trace(mVcdFile, knn_set_2_0_0_V_r, "(port)knn_set_2_0_0_V_r");
    sc_trace(mVcdFile, knn_set_2_0_1_V_r, "(port)knn_set_2_0_1_V_r");
    sc_trace(mVcdFile, knn_set_2_0_2_V_r, "(port)knn_set_2_0_2_V_r");
    sc_trace(mVcdFile, knn_set_2_1_0_V_r, "(port)knn_set_2_1_0_V_r");
    sc_trace(mVcdFile, knn_set_2_1_1_V_r, "(port)knn_set_2_1_1_V_r");
    sc_trace(mVcdFile, knn_set_2_1_2_V_r, "(port)knn_set_2_1_2_V_r");
    sc_trace(mVcdFile, knn_set_2_2_0_V_r, "(port)knn_set_2_2_0_V_r");
    sc_trace(mVcdFile, knn_set_2_2_1_V_r, "(port)knn_set_2_2_1_V_r");
    sc_trace(mVcdFile, knn_set_2_2_2_V_r, "(port)knn_set_2_2_2_V_r");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, sum_distances_1_min_s_fu_304_p3, "sum_distances_1_min_s_fu_304_p3");
    sc_trace(mVcdFile, sum_distances_1_min_s_reg_752, "sum_distances_1_min_s_reg_752");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, sum_distances_1_2_fu_334_p2, "sum_distances_1_2_fu_334_p2");
    sc_trace(mVcdFile, sum_distances_1_2_reg_757, "sum_distances_1_2_reg_757");
    sc_trace(mVcdFile, tmp_8_1_fu_340_p2, "tmp_8_1_fu_340_p2");
    sc_trace(mVcdFile, tmp_8_1_reg_762, "tmp_8_1_reg_762");
    sc_trace(mVcdFile, sum_distances_2_2_fu_368_p2, "sum_distances_2_2_fu_368_p2");
    sc_trace(mVcdFile, sum_distances_2_2_reg_768, "sum_distances_2_2_reg_768");
    sc_trace(mVcdFile, sum_distances_3_2_fu_396_p2, "sum_distances_3_2_fu_396_p2");
    sc_trace(mVcdFile, sum_distances_3_2_reg_774, "sum_distances_3_2_reg_774");
    sc_trace(mVcdFile, sum_distances_4_2_fu_424_p2, "sum_distances_4_2_fu_424_p2");
    sc_trace(mVcdFile, sum_distances_4_2_reg_780, "sum_distances_4_2_reg_780");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_sum_distances_4_2_reg_780, "ap_reg_pp0_iter1_sum_distances_4_2_reg_780");
    sc_trace(mVcdFile, sum_distances_5_2_fu_452_p2, "sum_distances_5_2_fu_452_p2");
    sc_trace(mVcdFile, sum_distances_5_2_reg_786, "sum_distances_5_2_reg_786");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_sum_distances_5_2_reg_786, "ap_reg_pp0_iter1_sum_distances_5_2_reg_786");
    sc_trace(mVcdFile, sum_distances_6_2_fu_480_p2, "sum_distances_6_2_fu_480_p2");
    sc_trace(mVcdFile, sum_distances_6_2_reg_792, "sum_distances_6_2_reg_792");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_sum_distances_6_2_reg_792, "ap_reg_pp0_iter1_sum_distances_6_2_reg_792");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_sum_distances_6_2_reg_792, "ap_reg_pp0_iter2_sum_distances_6_2_reg_792");
    sc_trace(mVcdFile, sum_distances_7_2_fu_508_p2, "sum_distances_7_2_fu_508_p2");
    sc_trace(mVcdFile, sum_distances_7_2_reg_798, "sum_distances_7_2_reg_798");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_sum_distances_7_2_reg_798, "ap_reg_pp0_iter1_sum_distances_7_2_reg_798");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_sum_distances_7_2_reg_798, "ap_reg_pp0_iter2_sum_distances_7_2_reg_798");
    sc_trace(mVcdFile, sum_distances_8_2_fu_536_p2, "sum_distances_8_2_fu_536_p2");
    sc_trace(mVcdFile, sum_distances_8_2_reg_804, "sum_distances_8_2_reg_804");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_sum_distances_8_2_reg_804, "ap_reg_pp0_iter1_sum_distances_8_2_reg_804");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_sum_distances_8_2_reg_804, "ap_reg_pp0_iter2_sum_distances_8_2_reg_804");
    sc_trace(mVcdFile, sum_distances_9_2_fu_564_p2, "sum_distances_9_2_fu_564_p2");
    sc_trace(mVcdFile, sum_distances_9_2_reg_810, "sum_distances_9_2_reg_810");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_sum_distances_9_2_reg_810, "ap_reg_pp0_iter1_sum_distances_9_2_reg_810");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_sum_distances_9_2_reg_810, "ap_reg_pp0_iter2_sum_distances_9_2_reg_810");
    sc_trace(mVcdFile, sum_distances_1_min_3_fu_592_p3, "sum_distances_1_min_3_fu_592_p3");
    sc_trace(mVcdFile, sum_distances_1_min_3_reg_815, "sum_distances_1_min_3_reg_815");
    sc_trace(mVcdFile, tmp_7_fu_616_p3, "tmp_7_fu_616_p3");
    sc_trace(mVcdFile, tmp_7_reg_821, "tmp_7_reg_821");
    sc_trace(mVcdFile, sum_distances_1_min_5_fu_639_p3, "sum_distances_1_min_5_fu_639_p3");
    sc_trace(mVcdFile, sum_distances_1_min_5_reg_826, "sum_distances_1_min_5_reg_826");
    sc_trace(mVcdFile, tmp_8_6_fu_646_p2, "tmp_8_6_fu_646_p2");
    sc_trace(mVcdFile, tmp_8_6_reg_831, "tmp_8_6_reg_831");
    sc_trace(mVcdFile, tmp_2_fu_668_p3, "tmp_2_fu_668_p3");
    sc_trace(mVcdFile, tmp_2_reg_837, "tmp_2_reg_837");
    sc_trace(mVcdFile, tmp_8_8_fu_693_p2, "tmp_8_8_fu_693_p2");
    sc_trace(mVcdFile, tmp_8_8_reg_842, "tmp_8_8_reg_842");
    sc_trace(mVcdFile, tmp_8_9_fu_705_p2, "tmp_8_9_fu_705_p2");
    sc_trace(mVcdFile, tmp_8_9_reg_847, "tmp_8_9_reg_847");
    sc_trace(mVcdFile, tmp_3_fu_723_p3, "tmp_3_fu_723_p3");
    sc_trace(mVcdFile, tmp_3_reg_853, "tmp_3_reg_853");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_1_0_2_cast_fu_278_p1, "tmp_1_0_2_cast_fu_278_p1");
    sc_trace(mVcdFile, tmp_1_cast_fu_270_p1, "tmp_1_cast_fu_270_p1");
    sc_trace(mVcdFile, tmp30_fu_282_p2, "tmp30_fu_282_p2");
    sc_trace(mVcdFile, tmp_1_0_1_cast_fu_274_p1, "tmp_1_0_1_cast_fu_274_p1");
    sc_trace(mVcdFile, tmp30_cast_fu_288_p1, "tmp30_cast_fu_288_p1");
    sc_trace(mVcdFile, sum_distances_0_2_fu_292_p2, "sum_distances_0_2_fu_292_p2");
    sc_trace(mVcdFile, tmp_8_fu_298_p2, "tmp_8_fu_298_p2");
    sc_trace(mVcdFile, tmp_1_1_2_cast_fu_320_p1, "tmp_1_1_2_cast_fu_320_p1");
    sc_trace(mVcdFile, tmp_1_1_cast_fu_312_p1, "tmp_1_1_cast_fu_312_p1");
    sc_trace(mVcdFile, tmp31_fu_324_p2, "tmp31_fu_324_p2");
    sc_trace(mVcdFile, tmp_1_1_1_cast_fu_316_p1, "tmp_1_1_1_cast_fu_316_p1");
    sc_trace(mVcdFile, tmp31_cast_fu_330_p1, "tmp31_cast_fu_330_p1");
    sc_trace(mVcdFile, tmp_1_2_2_cast_fu_354_p1, "tmp_1_2_2_cast_fu_354_p1");
    sc_trace(mVcdFile, tmp_1_2_cast_fu_346_p1, "tmp_1_2_cast_fu_346_p1");
    sc_trace(mVcdFile, tmp32_fu_358_p2, "tmp32_fu_358_p2");
    sc_trace(mVcdFile, tmp_1_2_1_cast_fu_350_p1, "tmp_1_2_1_cast_fu_350_p1");
    sc_trace(mVcdFile, tmp32_cast_fu_364_p1, "tmp32_cast_fu_364_p1");
    sc_trace(mVcdFile, tmp_1_3_2_cast_fu_382_p1, "tmp_1_3_2_cast_fu_382_p1");
    sc_trace(mVcdFile, tmp_1_3_cast_fu_374_p1, "tmp_1_3_cast_fu_374_p1");
    sc_trace(mVcdFile, tmp33_fu_386_p2, "tmp33_fu_386_p2");
    sc_trace(mVcdFile, tmp_1_3_1_cast_fu_378_p1, "tmp_1_3_1_cast_fu_378_p1");
    sc_trace(mVcdFile, tmp33_cast_fu_392_p1, "tmp33_cast_fu_392_p1");
    sc_trace(mVcdFile, tmp_1_4_2_cast_fu_410_p1, "tmp_1_4_2_cast_fu_410_p1");
    sc_trace(mVcdFile, tmp_1_4_cast_fu_402_p1, "tmp_1_4_cast_fu_402_p1");
    sc_trace(mVcdFile, tmp34_fu_414_p2, "tmp34_fu_414_p2");
    sc_trace(mVcdFile, tmp_1_4_1_cast_fu_406_p1, "tmp_1_4_1_cast_fu_406_p1");
    sc_trace(mVcdFile, tmp34_cast_fu_420_p1, "tmp34_cast_fu_420_p1");
    sc_trace(mVcdFile, tmp_1_5_2_cast_fu_438_p1, "tmp_1_5_2_cast_fu_438_p1");
    sc_trace(mVcdFile, tmp_1_5_cast_fu_430_p1, "tmp_1_5_cast_fu_430_p1");
    sc_trace(mVcdFile, tmp35_fu_442_p2, "tmp35_fu_442_p2");
    sc_trace(mVcdFile, tmp_1_5_1_cast_fu_434_p1, "tmp_1_5_1_cast_fu_434_p1");
    sc_trace(mVcdFile, tmp35_cast_fu_448_p1, "tmp35_cast_fu_448_p1");
    sc_trace(mVcdFile, tmp_1_6_2_cast_fu_466_p1, "tmp_1_6_2_cast_fu_466_p1");
    sc_trace(mVcdFile, tmp_1_6_cast_fu_458_p1, "tmp_1_6_cast_fu_458_p1");
    sc_trace(mVcdFile, tmp36_fu_470_p2, "tmp36_fu_470_p2");
    sc_trace(mVcdFile, tmp_1_6_1_cast_fu_462_p1, "tmp_1_6_1_cast_fu_462_p1");
    sc_trace(mVcdFile, tmp36_cast_fu_476_p1, "tmp36_cast_fu_476_p1");
    sc_trace(mVcdFile, tmp_1_7_2_cast_fu_494_p1, "tmp_1_7_2_cast_fu_494_p1");
    sc_trace(mVcdFile, tmp_1_7_cast_fu_486_p1, "tmp_1_7_cast_fu_486_p1");
    sc_trace(mVcdFile, tmp37_fu_498_p2, "tmp37_fu_498_p2");
    sc_trace(mVcdFile, tmp_1_7_1_cast_fu_490_p1, "tmp_1_7_1_cast_fu_490_p1");
    sc_trace(mVcdFile, tmp37_cast_fu_504_p1, "tmp37_cast_fu_504_p1");
    sc_trace(mVcdFile, tmp_1_8_2_cast_fu_522_p1, "tmp_1_8_2_cast_fu_522_p1");
    sc_trace(mVcdFile, tmp_1_8_cast_fu_514_p1, "tmp_1_8_cast_fu_514_p1");
    sc_trace(mVcdFile, tmp38_fu_526_p2, "tmp38_fu_526_p2");
    sc_trace(mVcdFile, tmp_1_8_1_cast_fu_518_p1, "tmp_1_8_1_cast_fu_518_p1");
    sc_trace(mVcdFile, tmp38_cast_fu_532_p1, "tmp38_cast_fu_532_p1");
    sc_trace(mVcdFile, tmp_1_9_2_cast_fu_550_p1, "tmp_1_9_2_cast_fu_550_p1");
    sc_trace(mVcdFile, tmp_1_9_cast_fu_542_p1, "tmp_1_9_cast_fu_542_p1");
    sc_trace(mVcdFile, tmp39_fu_554_p2, "tmp39_fu_554_p2");
    sc_trace(mVcdFile, tmp_1_9_1_cast_fu_546_p1, "tmp_1_9_1_cast_fu_546_p1");
    sc_trace(mVcdFile, tmp39_cast_fu_560_p1, "tmp39_cast_fu_560_p1");
    sc_trace(mVcdFile, sum_distances_1_min_1_fu_570_p3, "sum_distances_1_min_1_fu_570_p3");
    sc_trace(mVcdFile, tmp_8_2_fu_575_p2, "tmp_8_2_fu_575_p2");
    sc_trace(mVcdFile, sum_distances_1_min_2_fu_580_p3, "sum_distances_1_min_2_fu_580_p3");
    sc_trace(mVcdFile, tmp_8_3_fu_587_p2, "tmp_8_3_fu_587_p2");
    sc_trace(mVcdFile, tmp_6_fu_610_p2, "tmp_6_fu_610_p2");
    sc_trace(mVcdFile, tmp_5_fu_602_p3, "tmp_5_fu_602_p3");
    sc_trace(mVcdFile, tmp_cast_fu_599_p1, "tmp_cast_fu_599_p1");
    sc_trace(mVcdFile, tmp_8_4_fu_624_p2, "tmp_8_4_fu_624_p2");
    sc_trace(mVcdFile, sum_distances_1_min_4_fu_628_p3, "sum_distances_1_min_4_fu_628_p3");
    sc_trace(mVcdFile, tmp_8_5_fu_634_p2, "tmp_8_5_fu_634_p2");
    sc_trace(mVcdFile, tmp_s_fu_662_p2, "tmp_s_fu_662_p2");
    sc_trace(mVcdFile, tmp_9_fu_654_p3, "tmp_9_fu_654_p3");
    sc_trace(mVcdFile, tmp_7_cast_fu_651_p1, "tmp_7_cast_fu_651_p1");
    sc_trace(mVcdFile, sum_distances_1_min_6_fu_676_p3, "sum_distances_1_min_6_fu_676_p3");
    sc_trace(mVcdFile, tmp_8_7_fu_681_p2, "tmp_8_7_fu_681_p2");
    sc_trace(mVcdFile, sum_distances_1_min_7_fu_686_p3, "sum_distances_1_min_7_fu_686_p3");
    sc_trace(mVcdFile, sum_distances_1_min_8_fu_698_p3, "sum_distances_1_min_8_fu_698_p3");
    sc_trace(mVcdFile, tmp_4_fu_718_p2, "tmp_4_fu_718_p2");
    sc_trace(mVcdFile, tmp_3_cast_cast_fu_710_p3, "tmp_3_cast_cast_fu_710_p3");
    sc_trace(mVcdFile, tmp_10_fu_740_p2, "tmp_10_fu_740_p2");
    sc_trace(mVcdFile, tmp_1_fu_733_p3, "tmp_1_fu_733_p3");
    sc_trace(mVcdFile, tmp_10_cast_fu_730_p1, "tmp_10_cast_fu_730_p1");
    sc_trace(mVcdFile, knn_set_0_0_0_V_r_int_reg, "knn_set_0_0_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_0_1_V_r_int_reg, "knn_set_0_0_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_0_2_V_r_int_reg, "knn_set_0_0_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_0_3_V_r_int_reg, "knn_set_0_0_3_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_1_0_V_r_int_reg, "knn_set_0_1_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_1_1_V_r_int_reg, "knn_set_0_1_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_1_2_V_r_int_reg, "knn_set_0_1_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_1_3_V_r_int_reg, "knn_set_0_1_3_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_2_0_V_r_int_reg, "knn_set_0_2_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_2_1_V_r_int_reg, "knn_set_0_2_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_2_2_V_r_int_reg, "knn_set_0_2_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_0_2_3_V_r_int_reg, "knn_set_0_2_3_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_0_0_V_r_int_reg, "knn_set_1_0_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_0_1_V_r_int_reg, "knn_set_1_0_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_0_2_V_r_int_reg, "knn_set_1_0_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_1_0_V_r_int_reg, "knn_set_1_1_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_1_1_V_r_int_reg, "knn_set_1_1_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_1_2_V_r_int_reg, "knn_set_1_1_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_2_0_V_r_int_reg, "knn_set_1_2_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_2_1_V_r_int_reg, "knn_set_1_2_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_1_2_2_V_r_int_reg, "knn_set_1_2_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_0_0_V_r_int_reg, "knn_set_2_0_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_0_1_V_r_int_reg, "knn_set_2_0_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_0_2_V_r_int_reg, "knn_set_2_0_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_1_0_V_r_int_reg, "knn_set_2_1_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_1_1_V_r_int_reg, "knn_set_2_1_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_1_2_V_r_int_reg, "knn_set_2_1_2_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_2_0_V_r_int_reg, "knn_set_2_2_0_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_2_1_V_r_int_reg, "knn_set_2_2_1_V_r_int_reg");
    sc_trace(mVcdFile, knn_set_2_2_2_V_r_int_reg, "knn_set_2_2_2_V_r_int_reg");
#endif

    }
}

knn_vote::~knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void knn_vote::thread_ap_clk_no_reset_() {
    knn_set_0_0_0_V_r_int_reg = knn_set_0_0_0_V_r.read();
    knn_set_0_0_1_V_r_int_reg = knn_set_0_0_1_V_r.read();
    knn_set_0_0_2_V_r_int_reg = knn_set_0_0_2_V_r.read();
    knn_set_0_0_3_V_r_int_reg = knn_set_0_0_3_V_r.read();
    knn_set_0_1_0_V_r_int_reg = knn_set_0_1_0_V_r.read();
    knn_set_0_1_1_V_r_int_reg = knn_set_0_1_1_V_r.read();
    knn_set_0_1_2_V_r_int_reg = knn_set_0_1_2_V_r.read();
    knn_set_0_1_3_V_r_int_reg = knn_set_0_1_3_V_r.read();
    knn_set_0_2_0_V_r_int_reg = knn_set_0_2_0_V_r.read();
    knn_set_0_2_1_V_r_int_reg = knn_set_0_2_1_V_r.read();
    knn_set_0_2_2_V_r_int_reg = knn_set_0_2_2_V_r.read();
    knn_set_0_2_3_V_r_int_reg = knn_set_0_2_3_V_r.read();
    knn_set_1_0_0_V_r_int_reg = knn_set_1_0_0_V_r.read();
    knn_set_1_0_1_V_r_int_reg = knn_set_1_0_1_V_r.read();
    knn_set_1_0_2_V_r_int_reg = knn_set_1_0_2_V_r.read();
    knn_set_1_1_0_V_r_int_reg = knn_set_1_1_0_V_r.read();
    knn_set_1_1_1_V_r_int_reg = knn_set_1_1_1_V_r.read();
    knn_set_1_1_2_V_r_int_reg = knn_set_1_1_2_V_r.read();
    knn_set_1_2_0_V_r_int_reg = knn_set_1_2_0_V_r.read();
    knn_set_1_2_1_V_r_int_reg = knn_set_1_2_1_V_r.read();
    knn_set_1_2_2_V_r_int_reg = knn_set_1_2_2_V_r.read();
    knn_set_2_0_0_V_r_int_reg = knn_set_2_0_0_V_r.read();
    knn_set_2_0_1_V_r_int_reg = knn_set_2_0_1_V_r.read();
    knn_set_2_0_2_V_r_int_reg = knn_set_2_0_2_V_r.read();
    knn_set_2_1_0_V_r_int_reg = knn_set_2_1_0_V_r.read();
    knn_set_2_1_1_V_r_int_reg = knn_set_2_1_1_V_r.read();
    knn_set_2_1_2_V_r_int_reg = knn_set_2_1_2_V_r.read();
    knn_set_2_2_0_V_r_int_reg = knn_set_2_2_0_V_r.read();
    knn_set_2_2_1_V_r_int_reg = knn_set_2_2_1_V_r.read();
    knn_set_2_2_2_V_r_int_reg = knn_set_2_2_2_V_r.read();
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        ap_reg_pp0_iter1_sum_distances_4_2_reg_780 = sum_distances_4_2_reg_780.read();
        ap_reg_pp0_iter1_sum_distances_5_2_reg_786 = sum_distances_5_2_reg_786.read();
        ap_reg_pp0_iter1_sum_distances_6_2_reg_792 = sum_distances_6_2_reg_792.read();
        ap_reg_pp0_iter1_sum_distances_7_2_reg_798 = sum_distances_7_2_reg_798.read();
        ap_reg_pp0_iter1_sum_distances_8_2_reg_804 = sum_distances_8_2_reg_804.read();
        ap_reg_pp0_iter1_sum_distances_9_2_reg_810 = sum_distances_9_2_reg_810.read();
        ap_reg_pp0_iter2_sum_distances_6_2_reg_792 = ap_reg_pp0_iter1_sum_distances_6_2_reg_792.read();
        ap_reg_pp0_iter2_sum_distances_7_2_reg_798 = ap_reg_pp0_iter1_sum_distances_7_2_reg_798.read();
        ap_reg_pp0_iter2_sum_distances_8_2_reg_804 = ap_reg_pp0_iter1_sum_distances_8_2_reg_804.read();
        ap_reg_pp0_iter2_sum_distances_9_2_reg_810 = ap_reg_pp0_iter1_sum_distances_9_2_reg_810.read();
        sum_distances_1_2_reg_757 = sum_distances_1_2_fu_334_p2.read();
        sum_distances_1_min_3_reg_815 = sum_distances_1_min_3_fu_592_p3.read();
        sum_distances_1_min_5_reg_826 = sum_distances_1_min_5_fu_639_p3.read();
        sum_distances_1_min_s_reg_752 = sum_distances_1_min_s_fu_304_p3.read();
        sum_distances_2_2_reg_768 = sum_distances_2_2_fu_368_p2.read();
        sum_distances_3_2_reg_774 = sum_distances_3_2_fu_396_p2.read();
        sum_distances_4_2_reg_780 = sum_distances_4_2_fu_424_p2.read();
        sum_distances_5_2_reg_786 = sum_distances_5_2_fu_452_p2.read();
        sum_distances_6_2_reg_792 = sum_distances_6_2_fu_480_p2.read();
        sum_distances_7_2_reg_798 = sum_distances_7_2_fu_508_p2.read();
        sum_distances_8_2_reg_804 = sum_distances_8_2_fu_536_p2.read();
        sum_distances_9_2_reg_810 = sum_distances_9_2_fu_564_p2.read();
        tmp_2_reg_837 = tmp_2_fu_668_p3.read();
        tmp_3_reg_853 = tmp_3_fu_723_p3.read();
        tmp_7_reg_821 = tmp_7_fu_616_p3.read();
        tmp_8_1_reg_762 = tmp_8_1_fu_340_p2.read();
        tmp_8_6_reg_831 = tmp_8_6_fu_646_p2.read();
        tmp_8_8_reg_842 = tmp_8_8_fu_693_p2.read();
        tmp_8_9_reg_847 = tmp_8_9_fu_705_p2.read();
    }
}

void knn_vote::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void knn_vote::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void knn_vote::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void knn_vote::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void knn_vote::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void knn_vote::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void knn_vote::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void knn_vote::thread_ap_return() {
    ap_return = (!tmp_10_fu_740_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_10_fu_740_p2.read()[0].to_bool())? tmp_1_fu_733_p3.read(): tmp_10_cast_fu_730_p1.read());
}

void knn_vote::thread_sum_distances_0_2_fu_292_p2() {
    sum_distances_0_2_fu_292_p2 = (!tmp_1_0_1_cast_fu_274_p1.read().is_01() || !tmp30_cast_fu_288_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_0_1_cast_fu_274_p1.read()) + sc_biguint<8>(tmp30_cast_fu_288_p1.read()));
}

void knn_vote::thread_sum_distances_1_2_fu_334_p2() {
    sum_distances_1_2_fu_334_p2 = (!tmp_1_1_1_cast_fu_316_p1.read().is_01() || !tmp31_cast_fu_330_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_1_1_cast_fu_316_p1.read()) + sc_biguint<8>(tmp31_cast_fu_330_p1.read()));
}

void knn_vote::thread_sum_distances_1_min_1_fu_570_p3() {
    sum_distances_1_min_1_fu_570_p3 = (!tmp_8_1_reg_762.read()[0].is_01())? sc_lv<8>(): ((tmp_8_1_reg_762.read()[0].to_bool())? sum_distances_1_2_reg_757.read(): sum_distances_1_min_s_reg_752.read());
}

void knn_vote::thread_sum_distances_1_min_2_fu_580_p3() {
    sum_distances_1_min_2_fu_580_p3 = (!tmp_8_2_fu_575_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_8_2_fu_575_p2.read()[0].to_bool())? sum_distances_2_2_reg_768.read(): sum_distances_1_min_1_fu_570_p3.read());
}

void knn_vote::thread_sum_distances_1_min_3_fu_592_p3() {
    sum_distances_1_min_3_fu_592_p3 = (!tmp_8_3_fu_587_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_8_3_fu_587_p2.read()[0].to_bool())? sum_distances_3_2_reg_774.read(): sum_distances_1_min_2_fu_580_p3.read());
}

void knn_vote::thread_sum_distances_1_min_4_fu_628_p3() {
    sum_distances_1_min_4_fu_628_p3 = (!tmp_8_4_fu_624_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_8_4_fu_624_p2.read()[0].to_bool())? ap_reg_pp0_iter1_sum_distances_4_2_reg_780.read(): sum_distances_1_min_3_reg_815.read());
}

void knn_vote::thread_sum_distances_1_min_5_fu_639_p3() {
    sum_distances_1_min_5_fu_639_p3 = (!tmp_8_5_fu_634_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_8_5_fu_634_p2.read()[0].to_bool())? ap_reg_pp0_iter1_sum_distances_5_2_reg_786.read(): sum_distances_1_min_4_fu_628_p3.read());
}

void knn_vote::thread_sum_distances_1_min_6_fu_676_p3() {
    sum_distances_1_min_6_fu_676_p3 = (!tmp_8_6_reg_831.read()[0].is_01())? sc_lv<8>(): ((tmp_8_6_reg_831.read()[0].to_bool())? ap_reg_pp0_iter2_sum_distances_6_2_reg_792.read(): sum_distances_1_min_5_reg_826.read());
}

void knn_vote::thread_sum_distances_1_min_7_fu_686_p3() {
    sum_distances_1_min_7_fu_686_p3 = (!tmp_8_7_fu_681_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_8_7_fu_681_p2.read()[0].to_bool())? ap_reg_pp0_iter2_sum_distances_7_2_reg_798.read(): sum_distances_1_min_6_fu_676_p3.read());
}

void knn_vote::thread_sum_distances_1_min_8_fu_698_p3() {
    sum_distances_1_min_8_fu_698_p3 = (!tmp_8_8_fu_693_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_8_8_fu_693_p2.read()[0].to_bool())? ap_reg_pp0_iter2_sum_distances_8_2_reg_804.read(): sum_distances_1_min_7_fu_686_p3.read());
}

void knn_vote::thread_sum_distances_1_min_s_fu_304_p3() {
    sum_distances_1_min_s_fu_304_p3 = (!tmp_8_fu_298_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_8_fu_298_p2.read()[0].to_bool())? sum_distances_0_2_fu_292_p2.read(): ap_const_lv8_96);
}

void knn_vote::thread_sum_distances_2_2_fu_368_p2() {
    sum_distances_2_2_fu_368_p2 = (!tmp_1_2_1_cast_fu_350_p1.read().is_01() || !tmp32_cast_fu_364_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_2_1_cast_fu_350_p1.read()) + sc_biguint<8>(tmp32_cast_fu_364_p1.read()));
}

void knn_vote::thread_sum_distances_3_2_fu_396_p2() {
    sum_distances_3_2_fu_396_p2 = (!tmp_1_3_1_cast_fu_378_p1.read().is_01() || !tmp33_cast_fu_392_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_3_1_cast_fu_378_p1.read()) + sc_biguint<8>(tmp33_cast_fu_392_p1.read()));
}

void knn_vote::thread_sum_distances_4_2_fu_424_p2() {
    sum_distances_4_2_fu_424_p2 = (!tmp_1_4_1_cast_fu_406_p1.read().is_01() || !tmp34_cast_fu_420_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_4_1_cast_fu_406_p1.read()) + sc_biguint<8>(tmp34_cast_fu_420_p1.read()));
}

void knn_vote::thread_sum_distances_5_2_fu_452_p2() {
    sum_distances_5_2_fu_452_p2 = (!tmp_1_5_1_cast_fu_434_p1.read().is_01() || !tmp35_cast_fu_448_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_5_1_cast_fu_434_p1.read()) + sc_biguint<8>(tmp35_cast_fu_448_p1.read()));
}

void knn_vote::thread_sum_distances_6_2_fu_480_p2() {
    sum_distances_6_2_fu_480_p2 = (!tmp_1_6_1_cast_fu_462_p1.read().is_01() || !tmp36_cast_fu_476_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_6_1_cast_fu_462_p1.read()) + sc_biguint<8>(tmp36_cast_fu_476_p1.read()));
}

void knn_vote::thread_sum_distances_7_2_fu_508_p2() {
    sum_distances_7_2_fu_508_p2 = (!tmp_1_7_1_cast_fu_490_p1.read().is_01() || !tmp37_cast_fu_504_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_7_1_cast_fu_490_p1.read()) + sc_biguint<8>(tmp37_cast_fu_504_p1.read()));
}

void knn_vote::thread_sum_distances_8_2_fu_536_p2() {
    sum_distances_8_2_fu_536_p2 = (!tmp_1_8_1_cast_fu_518_p1.read().is_01() || !tmp38_cast_fu_532_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_8_1_cast_fu_518_p1.read()) + sc_biguint<8>(tmp38_cast_fu_532_p1.read()));
}

void knn_vote::thread_sum_distances_9_2_fu_564_p2() {
    sum_distances_9_2_fu_564_p2 = (!tmp_1_9_1_cast_fu_546_p1.read().is_01() || !tmp39_cast_fu_560_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_1_9_1_cast_fu_546_p1.read()) + sc_biguint<8>(tmp39_cast_fu_560_p1.read()));
}

void knn_vote::thread_tmp30_cast_fu_288_p1() {
    tmp30_cast_fu_288_p1 = esl_zext<8,7>(tmp30_fu_282_p2.read());
}

void knn_vote::thread_tmp30_fu_282_p2() {
    tmp30_fu_282_p2 = (!tmp_1_0_2_cast_fu_278_p1.read().is_01() || !tmp_1_cast_fu_270_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_0_2_cast_fu_278_p1.read()) + sc_biguint<7>(tmp_1_cast_fu_270_p1.read()));
}

void knn_vote::thread_tmp31_cast_fu_330_p1() {
    tmp31_cast_fu_330_p1 = esl_zext<8,7>(tmp31_fu_324_p2.read());
}

void knn_vote::thread_tmp31_fu_324_p2() {
    tmp31_fu_324_p2 = (!tmp_1_1_2_cast_fu_320_p1.read().is_01() || !tmp_1_1_cast_fu_312_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_1_2_cast_fu_320_p1.read()) + sc_biguint<7>(tmp_1_1_cast_fu_312_p1.read()));
}

void knn_vote::thread_tmp32_cast_fu_364_p1() {
    tmp32_cast_fu_364_p1 = esl_zext<8,7>(tmp32_fu_358_p2.read());
}

void knn_vote::thread_tmp32_fu_358_p2() {
    tmp32_fu_358_p2 = (!tmp_1_2_2_cast_fu_354_p1.read().is_01() || !tmp_1_2_cast_fu_346_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_2_2_cast_fu_354_p1.read()) + sc_biguint<7>(tmp_1_2_cast_fu_346_p1.read()));
}

void knn_vote::thread_tmp33_cast_fu_392_p1() {
    tmp33_cast_fu_392_p1 = esl_zext<8,7>(tmp33_fu_386_p2.read());
}

void knn_vote::thread_tmp33_fu_386_p2() {
    tmp33_fu_386_p2 = (!tmp_1_3_2_cast_fu_382_p1.read().is_01() || !tmp_1_3_cast_fu_374_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_3_2_cast_fu_382_p1.read()) + sc_biguint<7>(tmp_1_3_cast_fu_374_p1.read()));
}

void knn_vote::thread_tmp34_cast_fu_420_p1() {
    tmp34_cast_fu_420_p1 = esl_zext<8,7>(tmp34_fu_414_p2.read());
}

void knn_vote::thread_tmp34_fu_414_p2() {
    tmp34_fu_414_p2 = (!tmp_1_4_2_cast_fu_410_p1.read().is_01() || !tmp_1_4_cast_fu_402_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_4_2_cast_fu_410_p1.read()) + sc_biguint<7>(tmp_1_4_cast_fu_402_p1.read()));
}

void knn_vote::thread_tmp35_cast_fu_448_p1() {
    tmp35_cast_fu_448_p1 = esl_zext<8,7>(tmp35_fu_442_p2.read());
}

void knn_vote::thread_tmp35_fu_442_p2() {
    tmp35_fu_442_p2 = (!tmp_1_5_2_cast_fu_438_p1.read().is_01() || !tmp_1_5_cast_fu_430_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_5_2_cast_fu_438_p1.read()) + sc_biguint<7>(tmp_1_5_cast_fu_430_p1.read()));
}

void knn_vote::thread_tmp36_cast_fu_476_p1() {
    tmp36_cast_fu_476_p1 = esl_zext<8,7>(tmp36_fu_470_p2.read());
}

void knn_vote::thread_tmp36_fu_470_p2() {
    tmp36_fu_470_p2 = (!tmp_1_6_2_cast_fu_466_p1.read().is_01() || !tmp_1_6_cast_fu_458_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_6_2_cast_fu_466_p1.read()) + sc_biguint<7>(tmp_1_6_cast_fu_458_p1.read()));
}

void knn_vote::thread_tmp37_cast_fu_504_p1() {
    tmp37_cast_fu_504_p1 = esl_zext<8,7>(tmp37_fu_498_p2.read());
}

void knn_vote::thread_tmp37_fu_498_p2() {
    tmp37_fu_498_p2 = (!tmp_1_7_2_cast_fu_494_p1.read().is_01() || !tmp_1_7_cast_fu_486_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_7_2_cast_fu_494_p1.read()) + sc_biguint<7>(tmp_1_7_cast_fu_486_p1.read()));
}

void knn_vote::thread_tmp38_cast_fu_532_p1() {
    tmp38_cast_fu_532_p1 = esl_zext<8,7>(tmp38_fu_526_p2.read());
}

void knn_vote::thread_tmp38_fu_526_p2() {
    tmp38_fu_526_p2 = (!tmp_1_8_2_cast_fu_522_p1.read().is_01() || !tmp_1_8_cast_fu_514_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_8_2_cast_fu_522_p1.read()) + sc_biguint<7>(tmp_1_8_cast_fu_514_p1.read()));
}

void knn_vote::thread_tmp39_cast_fu_560_p1() {
    tmp39_cast_fu_560_p1 = esl_zext<8,7>(tmp39_fu_554_p2.read());
}

void knn_vote::thread_tmp39_fu_554_p2() {
    tmp39_fu_554_p2 = (!tmp_1_9_2_cast_fu_550_p1.read().is_01() || !tmp_1_9_cast_fu_542_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_1_9_2_cast_fu_550_p1.read()) + sc_biguint<7>(tmp_1_9_cast_fu_542_p1.read()));
}

void knn_vote::thread_tmp_10_cast_fu_730_p1() {
    tmp_10_cast_fu_730_p1 = esl_zext<4,3>(tmp_3_reg_853.read());
}

void knn_vote::thread_tmp_10_fu_740_p2() {
    tmp_10_fu_740_p2 = (tmp_8_9_reg_847.read() | tmp_8_8_reg_842.read());
}

void knn_vote::thread_tmp_1_0_1_cast_fu_274_p1() {
    tmp_1_0_1_cast_fu_274_p1 = esl_zext<8,6>(knn_set_0_1_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_0_2_cast_fu_278_p1() {
    tmp_1_0_2_cast_fu_278_p1 = esl_zext<7,6>(knn_set_0_2_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_1_1_cast_fu_316_p1() {
    tmp_1_1_1_cast_fu_316_p1 = esl_zext<8,6>(knn_set_1_1_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_1_2_cast_fu_320_p1() {
    tmp_1_1_2_cast_fu_320_p1 = esl_zext<7,6>(knn_set_1_2_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_1_cast_fu_312_p1() {
    tmp_1_1_cast_fu_312_p1 = esl_zext<7,6>(knn_set_1_0_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_2_1_cast_fu_350_p1() {
    tmp_1_2_1_cast_fu_350_p1 = esl_zext<8,6>(knn_set_2_1_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_2_2_cast_fu_354_p1() {
    tmp_1_2_2_cast_fu_354_p1 = esl_zext<7,6>(knn_set_2_2_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_2_cast_fu_346_p1() {
    tmp_1_2_cast_fu_346_p1 = esl_zext<7,6>(knn_set_2_0_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_3_1_cast_fu_378_p1() {
    tmp_1_3_1_cast_fu_378_p1 = esl_zext<8,6>(knn_set_0_1_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_3_2_cast_fu_382_p1() {
    tmp_1_3_2_cast_fu_382_p1 = esl_zext<7,6>(knn_set_0_2_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_3_cast_fu_374_p1() {
    tmp_1_3_cast_fu_374_p1 = esl_zext<7,6>(knn_set_0_0_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_4_1_cast_fu_406_p1() {
    tmp_1_4_1_cast_fu_406_p1 = esl_zext<8,6>(knn_set_1_1_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_4_2_cast_fu_410_p1() {
    tmp_1_4_2_cast_fu_410_p1 = esl_zext<7,6>(knn_set_1_2_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_4_cast_fu_402_p1() {
    tmp_1_4_cast_fu_402_p1 = esl_zext<7,6>(knn_set_1_0_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_5_1_cast_fu_434_p1() {
    tmp_1_5_1_cast_fu_434_p1 = esl_zext<8,6>(knn_set_2_1_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_5_2_cast_fu_438_p1() {
    tmp_1_5_2_cast_fu_438_p1 = esl_zext<7,6>(knn_set_2_2_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_5_cast_fu_430_p1() {
    tmp_1_5_cast_fu_430_p1 = esl_zext<7,6>(knn_set_2_0_1_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_6_1_cast_fu_462_p1() {
    tmp_1_6_1_cast_fu_462_p1 = esl_zext<8,6>(knn_set_0_1_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_6_2_cast_fu_466_p1() {
    tmp_1_6_2_cast_fu_466_p1 = esl_zext<7,6>(knn_set_0_2_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_6_cast_fu_458_p1() {
    tmp_1_6_cast_fu_458_p1 = esl_zext<7,6>(knn_set_0_0_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_7_1_cast_fu_490_p1() {
    tmp_1_7_1_cast_fu_490_p1 = esl_zext<8,6>(knn_set_1_1_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_7_2_cast_fu_494_p1() {
    tmp_1_7_2_cast_fu_494_p1 = esl_zext<7,6>(knn_set_1_2_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_7_cast_fu_486_p1() {
    tmp_1_7_cast_fu_486_p1 = esl_zext<7,6>(knn_set_1_0_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_8_1_cast_fu_518_p1() {
    tmp_1_8_1_cast_fu_518_p1 = esl_zext<8,6>(knn_set_2_1_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_8_2_cast_fu_522_p1() {
    tmp_1_8_2_cast_fu_522_p1 = esl_zext<7,6>(knn_set_2_2_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_8_cast_fu_514_p1() {
    tmp_1_8_cast_fu_514_p1 = esl_zext<7,6>(knn_set_2_0_2_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_9_1_cast_fu_546_p1() {
    tmp_1_9_1_cast_fu_546_p1 = esl_zext<8,6>(knn_set_0_1_3_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_9_2_cast_fu_550_p1() {
    tmp_1_9_2_cast_fu_550_p1 = esl_zext<7,6>(knn_set_0_2_3_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_9_cast_fu_542_p1() {
    tmp_1_9_cast_fu_542_p1 = esl_zext<7,6>(knn_set_0_0_3_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_cast_fu_270_p1() {
    tmp_1_cast_fu_270_p1 = esl_zext<7,6>(knn_set_0_0_0_V_r_int_reg.read());
}

void knn_vote::thread_tmp_1_fu_733_p3() {
    tmp_1_fu_733_p3 = (!tmp_8_9_reg_847.read()[0].is_01())? sc_lv<4>(): ((tmp_8_9_reg_847.read()[0].to_bool())? ap_const_lv4_9: ap_const_lv4_8);
}

void knn_vote::thread_tmp_2_fu_668_p3() {
    tmp_2_fu_668_p3 = (!tmp_s_fu_662_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_s_fu_662_p2.read()[0].to_bool())? tmp_9_fu_654_p3.read(): tmp_7_cast_fu_651_p1.read());
}

void knn_vote::thread_tmp_3_cast_cast_fu_710_p3() {
    tmp_3_cast_cast_fu_710_p3 = (!tmp_8_7_fu_681_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_8_7_fu_681_p2.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_6);
}

void knn_vote::thread_tmp_3_fu_723_p3() {
    tmp_3_fu_723_p3 = (!tmp_4_fu_718_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_4_fu_718_p2.read()[0].to_bool())? tmp_3_cast_cast_fu_710_p3.read(): tmp_2_reg_837.read());
}

void knn_vote::thread_tmp_4_fu_718_p2() {
    tmp_4_fu_718_p2 = (tmp_8_7_fu_681_p2.read() | tmp_8_6_reg_831.read());
}

void knn_vote::thread_tmp_5_fu_602_p3() {
    tmp_5_fu_602_p3 = (!tmp_8_3_fu_587_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_8_3_fu_587_p2.read()[0].to_bool())? ap_const_lv2_3: ap_const_lv2_2);
}

void knn_vote::thread_tmp_6_fu_610_p2() {
    tmp_6_fu_610_p2 = (tmp_8_3_fu_587_p2.read() | tmp_8_2_fu_575_p2.read());
}

void knn_vote::thread_tmp_7_cast_fu_651_p1() {
    tmp_7_cast_fu_651_p1 = esl_zext<3,2>(tmp_7_reg_821.read());
}

void knn_vote::thread_tmp_7_fu_616_p3() {
    tmp_7_fu_616_p3 = (!tmp_6_fu_610_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_6_fu_610_p2.read()[0].to_bool())? tmp_5_fu_602_p3.read(): tmp_cast_fu_599_p1.read());
}

void knn_vote::thread_tmp_8_1_fu_340_p2() {
    tmp_8_1_fu_340_p2 = (!sum_distances_1_2_fu_334_p2.read().is_01() || !sum_distances_1_min_s_fu_304_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_distances_1_2_fu_334_p2.read()) < sc_biguint<8>(sum_distances_1_min_s_fu_304_p3.read()));
}

void knn_vote::thread_tmp_8_2_fu_575_p2() {
    tmp_8_2_fu_575_p2 = (!sum_distances_2_2_reg_768.read().is_01() || !sum_distances_1_min_1_fu_570_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_distances_2_2_reg_768.read()) < sc_biguint<8>(sum_distances_1_min_1_fu_570_p3.read()));
}

void knn_vote::thread_tmp_8_3_fu_587_p2() {
    tmp_8_3_fu_587_p2 = (!sum_distances_3_2_reg_774.read().is_01() || !sum_distances_1_min_2_fu_580_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(sum_distances_3_2_reg_774.read()) < sc_biguint<8>(sum_distances_1_min_2_fu_580_p3.read()));
}

void knn_vote::thread_tmp_8_4_fu_624_p2() {
    tmp_8_4_fu_624_p2 = (!ap_reg_pp0_iter1_sum_distances_4_2_reg_780.read().is_01() || !sum_distances_1_min_3_reg_815.read().is_01())? sc_lv<1>(): (sc_biguint<8>(ap_reg_pp0_iter1_sum_distances_4_2_reg_780.read()) < sc_biguint<8>(sum_distances_1_min_3_reg_815.read()));
}

void knn_vote::thread_tmp_8_5_fu_634_p2() {
    tmp_8_5_fu_634_p2 = (!ap_reg_pp0_iter1_sum_distances_5_2_reg_786.read().is_01() || !sum_distances_1_min_4_fu_628_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(ap_reg_pp0_iter1_sum_distances_5_2_reg_786.read()) < sc_biguint<8>(sum_distances_1_min_4_fu_628_p3.read()));
}

void knn_vote::thread_tmp_8_6_fu_646_p2() {
    tmp_8_6_fu_646_p2 = (!ap_reg_pp0_iter1_sum_distances_6_2_reg_792.read().is_01() || !sum_distances_1_min_5_fu_639_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(ap_reg_pp0_iter1_sum_distances_6_2_reg_792.read()) < sc_biguint<8>(sum_distances_1_min_5_fu_639_p3.read()));
}

void knn_vote::thread_tmp_8_7_fu_681_p2() {
    tmp_8_7_fu_681_p2 = (!ap_reg_pp0_iter2_sum_distances_7_2_reg_798.read().is_01() || !sum_distances_1_min_6_fu_676_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(ap_reg_pp0_iter2_sum_distances_7_2_reg_798.read()) < sc_biguint<8>(sum_distances_1_min_6_fu_676_p3.read()));
}

void knn_vote::thread_tmp_8_8_fu_693_p2() {
    tmp_8_8_fu_693_p2 = (!ap_reg_pp0_iter2_sum_distances_8_2_reg_804.read().is_01() || !sum_distances_1_min_7_fu_686_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(ap_reg_pp0_iter2_sum_distances_8_2_reg_804.read()) < sc_biguint<8>(sum_distances_1_min_7_fu_686_p3.read()));
}

void knn_vote::thread_tmp_8_9_fu_705_p2() {
    tmp_8_9_fu_705_p2 = (!ap_reg_pp0_iter2_sum_distances_9_2_reg_810.read().is_01() || !sum_distances_1_min_8_fu_698_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(ap_reg_pp0_iter2_sum_distances_9_2_reg_810.read()) < sc_biguint<8>(sum_distances_1_min_8_fu_698_p3.read()));
}

void knn_vote::thread_tmp_8_fu_298_p2() {
    tmp_8_fu_298_p2 = (!sum_distances_0_2_fu_292_p2.read().is_01() || !ap_const_lv8_96.is_01())? sc_lv<1>(): (sc_biguint<8>(sum_distances_0_2_fu_292_p2.read()) < sc_biguint<8>(ap_const_lv8_96));
}

void knn_vote::thread_tmp_9_fu_654_p3() {
    tmp_9_fu_654_p3 = (!tmp_8_5_fu_634_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_8_5_fu_634_p2.read()[0].to_bool())? ap_const_lv3_5: ap_const_lv3_4);
}

void knn_vote::thread_tmp_cast_fu_599_p1() {
    tmp_cast_fu_599_p1 = esl_zext<2,1>(tmp_8_1_reg_762.read());
}

void knn_vote::thread_tmp_s_fu_662_p2() {
    tmp_s_fu_662_p2 = (tmp_8_5_fu_634_p2.read() | tmp_8_4_fu_624_p2.read());
}

}

